Kernel/cpu-z180/z180.def
Kernel/cpu-z180/z180.h
Kernel/dev/ds1302.c
Kernel/dev/ds1302.h
Kernel/platform-n8vem-mark4/Makefile
Kernel/platform-n8vem-mark4/config.h
Kernel/platform-n8vem-mark4/crt0.s
Kernel/platform-n8vem-mark4/devices.c
Kernel/platform-n8vem-mark4/ds1302-mark4.s
Kernel/platform-n8vem-mark4/kernel.def
Kernel/platform-n8vem-mark4/uzi.lnk
Kernel/platform-p112/Makefile
Kernel/platform-p112/config.h
Kernel/platform-p112/crt0.s
Kernel/platform-p112/devices.c
Kernel/platform-p112/ds1302-p112.s
Kernel/platform-p112/uzi.lnk
Kernel/timer.c

Alan
Happy new year!
This pull request is for a driver for the DS1302/DS1202 RTC chip which is used on both p112 and n8vem-mark4.
It is structured in a similar style to the SD driver, ie one generic driver that knows how to talk to the chip, and per-platform drivers that implement the actual hardware operations. The platform drivers are both written in assembler as I found sdcc generated quite verbose code for small functions when I wrote them in C. I also tried using one C function that manipulated all the hardware pins but it just made the code hard to follow.
On boot the ds1302_init() function is called from the platform setup code. This reads out the full RTC date and time, converts to posix time, and calls wrtime(). One problem I found with this was that naively telling the compiler …

DS1302/DS1202 RTC driver

---

Kernel/cpu-z180/z180.s

This (I hope!) fixes startup code for situations where RAM does not start at physical address 0 and where the kernel is loaded into the first 64K of RAM but not where we ultimately want it to end up.

Kernel: Fix Z180 startup code

---

Kernel/platform-msx2/Makefile
Kernel/platform-msx2/config.h
Kernel/platform-msx2/devices.c
Kernel/platform-msx2/devmegasd.c
Kernel/platform-msx2/fuzix.lnk

using the generic devsd driver maybe is not the fastest option because we need
to switch slots many times when sending commands, but it works as expected and
performance is acceptable for now.

msx2: add MegaSD driver

---

Applications/util/Makefile
Applications/util/cmp.c
Library/include/stdlib.h
Library/libs/ltoa.c
Library/libs/ltostr.c
Library/libs/tcflow.c
Library/libs/vfprintf.c
Library/libs/xitoa.c
Library/tools/libclean

Alan
Here are the fixes to ltoa, strtol and friends plus associated fixes. Checked library and all utils build. I found there were some duplicate symbols in syslib.lib, mostly that we were importing from the SDCC libraries and also implementing ourselves, fixed by dropping the SDCC versions. We also had two implementations of tcflush(), one hiding inside tcflow.c. That's also fixed although we are still lacking a tcflow() function -- I've made a stub that returns an error for now.
Will

Fixes to standard library

---

Kernel/dev/blkdev.c
Kernel/dev/blkdev.h
Kernel/dev/devide.c
Kernel/dev/devide.h
Kernel/dev/devsd.c
Kernel/dev/devsd.h
Kernel/dev/mbr.c
Kernel/dev/mbr.h
Kernel/include/kernel.h
Kernel/platform-msx2/Makefile
Kernel/platform-msx2/config.h
Kernel/platform-msx2/devices.c
Kernel/platform-msx2/fuzix.lnk
Kernel/platform-n8vem-mark4/Makefile
Kernel/platform-n8vem-mark4/config.h
Kernel/platform-n8vem-mark4/devices.c
Kernel/platform-n8vem-mark4/fuzix.lnk
Kernel/platform-p112/Makefile
Kernel/platform-p112/config.h
Kernel/platform-p112/devices.c
Kernel/platform-p112/fuzix.lnk

Hardware drivers are now responsible for the bare mimumum -- identify
the storage devices present, figure out how large they are, and provide
a function to read/write sectors.
The concept of "slices" goes away, instead we will use a separate
partition for each file system.
The blkdev layer handles PC-style MBR partition tables, both primary and
extended partitions, up to a maximum of 15 partitions per drive. The
partition numbering is chosen to be compatible with Linux.
Storage drivers no longer each require a separate entry in the device
switch table.
This includes patches for n8vem-mark4, p112 and msx2 all of which are using
devsd or devide.

Introduce new "blkdev" layer for 512-byte sector partitioned drives.

---

Kernel/dev/mbr.c

Overall this branch now saves (drumroll) 16 bytes! Also includes an important bug fix.

mbr: Save 16 bytes, fix bug

---

Kernel/tools/binman.c

_DISCARD can grow to overlap _COMMONMEM, linker is happy with this, makebin is happy with the overwriting in the .ihx, only binman can save us now!

binman: tidy up, fail when _DISCARD grows to overlap _COMMONMEM

---

Kernel/Makefile

tools/bankld can use Makefile
tools/bihx and tools/bintomdv are built in the Makefile
common.ihx, common.bin, and relocs.dat are outputs from tools/binhx

Makefile: add missing clean targets

---

Kernel/cpu-z80/cpu.h
Kernel/dev/devide.c
Kernel/dev/mbr.c

This addresses the little-endian assumptions in devide and mbr.

devide, mbr: Remove little endian assumptions

---

Kernel/lib/monitor-z80.s
Kernel/platform-n8vem-mark4/Makefile
Kernel/platform-n8vem-mark4/fuzix.lnk
Kernel/platform-n8vem-mark4/kernel.def
Kernel/platform-n8vem-mark4/mark4.s
Kernel/platform-n8vem-mark4/monitor.s
Kernel/platform-p112/Makefile
Kernel/platform-p112/fuzix.lnk
Kernel/platform-p112/kernel.def
Kernel/platform-p112/monitor.s
Kernel/platform-p112/p112.s

Platform must provide an "inchar" routine which waits for a character on the console and returns it in A.
This patch also implements the monitor on the p112 and n8vem-mark4 platforms.
The feature can be optionally disabled, saving a little under 0.5KB common memory.

Kernel: Simple monitor program for Z80 and Z180, useful for inspecting machine state.

---

Kernel/cpu-z180/z180.def
Kernel/platform-p112/Makefile
Kernel/platform-p112/README
Kernel/platform-p112/config.h
Kernel/platform-p112/devfd.c
Kernel/platform-p112/devfd.h
Kernel/platform-p112/devfd2.s
Kernel/platform-p112/devices.c
Kernel/platform-p112/flopboot-mkimage
Kernel/platform-p112/flopboot.s
Kernel/platform-p112/fuzix.lnk
Kernel/platform-p112/main.c
Kernel/platform-p112/p112.s

The driver for the SMC floppy disk controller is a straight port of the
driver from UZI-180. It uses neither DMA nor interrupts.
The p112 platform can now be booted from floppy disk. The current boot
sector is somewhat rudimentary and requires the floppy disk to be
dedicated to the kernel (it cannot also hold a Fuzix filesystem).

Kernel: p112 floppy disk driver and floppy disk boot support

---

Library/libs/vfprintf.c

Fixes %x etc with vfprintf. We were passing a negative radix to __ultostr() which proceeded to fail.

Library: Bug fix for vfprintf()

---

Kernel/cpu-z80/cpu.h
Kernel/dev/blkdev.c
Kernel/dev/blkdev.h
Kernel/dev/devide.c
Kernel/dev/devsd.c
Kernel/dev/devsd.h
Kernel/dev/mbr.c
Kernel/dev/mbr.h
Kernel/lib/monitor-z80.s
Kernel/platform-n8vem-mark4/devsdspi.c
Kernel/syscall_exec.c

This adds support for rawflag=1 to blkdev, devide and devsd. It updates the mark4-n8vem SD code to the new API. Also fixes a bug in syscall_exec. And despite all that it uses 54 bytes less memory.

blkdev and friends: Update to support rawflag=1

---

Applications/util/dd.c
Kernel/devio.c
Kernel/filesys.c
Kernel/include/kernel.h
Kernel/start.c
Kernel/syscall_other.c

Also only includes bufdump() if CONFIG_IDUMP is set (since that is the only place from which it is called).

Fix for unmounting filesystem, fix for dd count= option, change bf_free to tristate for unfreeable superblocks

---

Kernel/Makefile
Kernel/platform-8086test/rules.mk
Kernel/platform-atarist/rules.mk
Kernel/platform-dragon/rules.mk
Kernel/platform-n8vem-mark4/README
Kernel/platform-n8vem-mark4/rules.mk
Kernel/platform-p112/README
Kernel/platform-p112/rules.mk
Kernel/platform-socz80/rules.mk
Kernel/platform-tgl6502/rules.mk
Kernel/platform-z80pack-lite/rules.mk
Kernel/platform-z80pack/rules.mk
Kernel/platform-zx128/rules.mk

This means that only the PLATFORM variable needs to be specified in
Kernel/Makefile, instead both PLATFORM and CPU in combination.

Kernel: The platform rules.mk should define the CPU used

---

Kernel/inode.c
Kernel/platform-n8vem-mark4/config.h
Kernel/platform-p112/config.h

Similar could be done for writei() if required.

Kernel: readi() - when reading whole sectors, transfer them directly into user memory.

---

Kernel/Makefile
Kernel/include/kdata.h
Kernel/kdata.c
Kernel/platform-n8vem-mark4/Makefile
Kernel/platform-n8vem-mark4/README
Kernel/platform-n8vem-mark4/config.h
Kernel/platform-n8vem-mark4/discard.c
Kernel/platform-n8vem-mark4/fuzix.lnk
Kernel/platform-n8vem-mark4/main.c
Kernel/platform-p112/Makefile
Kernel/platform-p112/README
Kernel/platform-p112/config.h
Kernel/platform-p112/discard.c
Kernel/platform-p112/fuzix.lnk
Kernel/platform-p112/main.c
Kernel/start.c

With these changes you can specify (eg) "hdb1" or "fd0" at the boot device prompt (or on the command line). Backward compatible with the old numeric parsing.

Better root device name parsing

---

Kernel/platform-msx2/Makefile
Kernel/platform-msx2/devtty.c
Kernel/platform-msx2/discard.c
Kernel/platform-msx2/kbdmatrix.h

also move some code to CODE2 to avoid overlapping of BOOT.
I think I will prepare a patch to switch to a banked rom cartridge instead of the linear one we have now; that will solve the problem of overlaps and will also make the bootstrap discardable.

move keyboard matrices to discard

---

Kernel/cpu-z180/z180.s
Kernel/include/tty.h
Kernel/platform-p112/README
Kernel/platform-p112/config.h
Kernel/platform-p112/devices.c
Kernel/platform-p112/devtty.c
Kernel/platform-p112/devtty.h
Kernel/platform-p112/discard.c
Kernel/platform-p112/flopboot-mkimage
Kernel/platform-p112/main.c
Kernel/platform-p112/p112.s
Kernel/process.c
Kernel/tty.c
Standalone/filesystem-src/ucp-script.txt

I've been working on improving serial support.
The P112 has no fewer than three different UART types and so I've been working on supporting them all. This patch hugely improves flow control for output on the ESCC and 16550A ports. It also addresses a race where we can put a writing process to sleep and never awaken it (explained in more detail in the relevant commit, b313216).
Still work to do on this front: CTS for the ASCI ports, and ultimately RTS for all of them too. This will need tty_inproc() to signal when RTS should fall and also some mechanism to raise RTS again. I need to make up a cable with a level shifter to get access to the ASCI ports.

Improved P112 serial support

---

Kernel/platform-msx2/Makefile
Kernel/platform-msx2/bootrom.s
Kernel/platform-msx2/crt0.s
Kernel/platform-msx2/fuzix.lnk
Kernel/platform-msx2/fuzix_boot.lnk
Kernel/platform-msx2/image.mk
Kernel/platform-msx2/msx2.def
Kernel/platform-msx2/msx2.s

Switching to a banked rom simplifies the bootstrap, allows us to
discard it and also opens the possibility of appending a romfs
after the kernel

msx2: generate 8k banked ascii rom

---

Kernel/platform-zeta-v2/README
Kernel/platform-zeta-v2/config.h
Kernel/platform-zeta-v2/devrd.c
Kernel/platform-zeta-v2/devrd_hw.s
Kernel/platform-zeta-v2/tricks.s
Kernel/platform-zeta-v2/zeta-v2.s

As discussed I modified RAM disk code to update the MPGSEL (MMU page select) registers cache, so that now it can run with interrupts enabled (in case of interrupt map_save will have valid page numbers).
It also has several other minor fixes:
* rd added to BOOTDEVICENAMES
* README updates:
- Updated device names and numbers for block devices
- rd0 can be used as a boot device
- Fixed cut-and-paste error in dd command line

zeta-v2: RAM disk cleanup, README fixes

---

Kernel/dev/devsd.c
Kernel/dev/devsd.h
Kernel/dev/devsd_discard.c
Kernel/platform-msx2/devmegasd.c
Kernel/platform-n8vem-mark4/devsdspi.c
Kernel/platform-socz80/devsdspi.c

None of our existing platforms support multiple cards. This change moves
the SD drive number into a global variable which platform drivers can
access if required.
This change reduces code size by just over 200 bytes.

devsd: Do not pass drive number as function argument

---

Kernel/platform-zeta-v2/devtty.c
Kernel/platform-zeta-v2/devtty.h
Kernel/platform-zeta-v2/kernel.def
Kernel/platform-zeta-v2/main.c
Kernel/platform-zeta-v2/zeta-v2.s
Library/tools/fcc.c

Added Will's 16550A UART code. Implemented tty_setup.
TODO: Auto-detect UART type, at least detect if UART has a working FIFO. (This is not a problem for P112, since it always has the 16550A-type UART with FIFO, but it could be an issue for Zeta, where builders can stick any UART they have).

zeta-v2: adopt UART code from P112, implement tty_setup

---

Kernel/platform-zeta-v2/Makefile
Kernel/platform-zeta-v2/devices.c
Kernel/platform-zeta-v2/devtty.c
Kernel/platform-zeta-v2/devtty.h
Kernel/platform-zeta-v2/devtty_discard.c
Kernel/platform-zeta-v2/discard.c
Kernel/platform-zeta-v2/fuzix.lnk
Kernel/platform-zeta-v2/zeta-v2.s

This patch adds UART type and capabilities auto detection.
Currently it can detect 8250, 8250A/16450, 16550 (broken FIFO), and 16550A. It also determines if 16550A  supports auto-flow control (e.g. TI TL16C550C and NXP SC16C550B).
TODO: Detect UARTs with EFR (e.g. Exar ST16C650 and XR16C850).

zeta-v2: Add UART type autodetection

---

Applications/util/factor.c

It should have been argv, because `char**`.

Fixed type error

---

Applications/util/df.c
Applications/util/mknod.c
Applications/util/mount.c
Applications/util/ssh.c
Applications/util/umount.c
Applications/util/uud.c

This takes calls to scanf out of some of the applications, reducing the size of the binaries significantly. (mknod, which is nigh trivial but which calls out to both printf and scanf, won't fit on a small system I'm working on.)

Remove scanf dependencies to reduce the size of the apps

---

Library/include/stdlib.h
Library/include/string.h
Library/include/syscalls.h
Library/libs/bcmp.c
Library/libs/bzero.c
Library/libs/calloc.c
Library/libs/memchr.c
Library/libs/memcmp.c
Library/libs/memcpy.c
Library/libs/memmove.c
Library/libs/memset.c
Library/libs/putchar.c
Library/libs/setbuffer.c
Library/libs/strcat.c
Library/libs/strchr.c
Library/libs/strcmp.c
Library/libs/strcpy.c
Library/libs/strcspn.c
Library/libs/strlen.c
Library/libs/strncat.c
Library/libs/strncmp.c
Library/libs/strncpy.c
Library/libs/strrchr.c
Library/libs/vfprintf.c
Library/libs/vfscanf.c

This is a whole bunch of relatively minor libc changes:
- prototyping and function signature changes to be more consistent and standard
- replace the unused Z80 versions of the string functions with portable C versions (stolen from the ACK; 3-clause BSD licensed); Z80 platform use the copies from the compiler library anyway, and having C versions is required by platforms that don't have these in their compiler library
- some relatively minor changes to printf and scanf to reduce code size (by a few hundred bytes).

Libc tweaks

---

Applications/V7/cmd/at.c
Applications/V7/cmd/col.c
Applications/V7/cmd/comm.c
Applications/V7/cmd/cron.c
Applications/V7/cmd/crypt.c
Applications/V7/cmd/dc.c
Applications/V7/cmd/dd.c
Applications/V7/cmd/deroff.c
Applications/V7/cmd/diff.c
Applications/V7/cmd/diff3.c
Applications/V7/cmd/diffh.c
Applications/V7/cmd/join.c
Applications/V7/cmd/pr.c
Applications/V7/cmd/ptx.c
Applications/V7/cmd/rev.c
Applications/V7/cmd/split.c
Applications/V7/cmd/su.c
Applications/V7/cmd/sum.c
Applications/V7/cmd/test.c
Applications/V7/cmd/time.c
Applications/V7/cmd/tsort.c
Applications/V7/cmd/wall.c
Applications/V7/games/arithmetic.c
Applications/V7/games/fish.c
Applications/V7/games/wump.c
Library/libs/execl.c

Ansification, constification and smallifying pass --- now builds on 6502 and Z80 (and without warnings on gcc5). Added dummy execl and execlp implementations for cc65 as at requires them.
The biggest 6502 app is still levee, at 48309 bytes, but dc is close behind at 47716 bytes. I haven't been able to run anything, though.

V7 app fixes

---

Kernel/platform-zeta-v2/Makefile
Kernel/platform-zeta-v2/bootrom.s
Kernel/platform-zeta-v2/config.h
Kernel/platform-zeta-v2/crt0.s
Kernel/platform-zeta-v2/devtty.c
Kernel/platform-zeta-v2/kernel.def
Kernel/platform-zeta-v2/zeta-v2.h
Kernel/platform-zeta-v2/zeta-v2.s

We no longer change tty1 UART parameters unless booting from ROM, this means it is not necessary to keep the BIOS UART config in sync with the kernel UART config.

zeta-v2: Fix boot from kernel in ROM

---

Applications/V7/cmd/diff.c
Applications/V7/cmd/time.c
Applications/util/cal.c
Applications/util/cat.c
Applications/util/chmod.c
Applications/util/cksum.c
Applications/util/cmp.c
Applications/util/df.c
Applications/util/dosread.c
Applications/util/du.c
Applications/util/ed.c
Applications/util/fsck.c
Applications/util/init.c
Applications/util/ll.c
Applications/util/ls.c
Applications/util/man.c
Applications/util/mkdir.c
Applications/util/od.c
Applications/util/ps.c
Applications/util/ssh.c
Applications/util/stty.c
Applications/util/sum.c
Applications/util/tee.c
Applications/util/tr.c
Applications/util/uue.c
Applications/util/which.c
Applications/util/write.c
Library/libs/strstr.c

This is a set of simple changes intended to make the apps build with cc65. It pulls out some stack-allocated buffers into global variables, to keep the stack size down, and also adds explicit casts to work around some of cc65's type comparison bugs.

Some cc65 fixes

---

.travis.yml

Rather than downloading and building sdcc ourselves, use the precompiled version in my PPA. This reduces build time from about 8 minutes to about 5.

Use precompiled sdcc for Travis builds

---

Kernel/platform-zeta-v2/zeta-v2.s

This makes _trap_reboot compatible with UNA BIOS on Zeta 2 SBC.

zeta-v2: _trap_reboot now disables memory paging entirely

---

Kernel/platform-coco3/boot/boot.s

Old code only worked with the ' comment in BASIC. Now the REM token will also work for passing command line to kernel. (Thanks William Astle)

coco3: boot: commandline works with REM token.

---

Kernel/dev/blkdev.c

The main sector transfer loop, was just sending the low-level driver the same address and lba every loop....

blkdev: increment data address and lba each time through read/write loop

---

Kernel/platform-coco3/mbr.c

Needed to convert offsets / lens in the partition table to 512b block addressing, as our partition table can be formated in 256, 512, 1024.... etc...

coco3: bugfix: mbr.c adjust offsets/lens for 512b blocks.

---

Kernel/platform-coco3/coco3.s

This was glitching out my TV.  I forgot I live in N. America. :)

coco3: bugfix: don't set PAL mode for the coco3.

---

Kernel/platform-coco3/devtty.c

Until we figure out how to do a back-tick on the dragon/coco2.

coco3: keyboard does `, console displays as UP_ARROW.

---

Applications/V7/cmd/sh/args.c
Applications/V7/cmd/sh/defs.h
Applications/V7/cmd/sh/expand.c
Applications/V7/cmd/sh/fault.c
Applications/V7/cmd/sh/io.c
Applications/V7/cmd/sh/main.c
Applications/V7/cmd/sh/service.c

This allows sh to build and run on Linux.
(I was debugging a horrible issue elsewhere and found myself needing to step through the sh memory allocation code in gdb. The sh innards are rather scary. And, it turned out, completely correct AFAICT.)

sh now builds and runs on modern computers.

---

Kernel/cpu-msp430x/cpu.h
Kernel/platform-msp430fr5969/config.h

This fixes a couple of trivial bugs in your recent changes that were stopping the MSP430 from building.
I also figured out the proper magic numbers. Turns out the test costs 18 bytes of code space...

Minor MSP430 fixes

---

Kernel/platform-coco3/coco3.s

The CoCo3 fpga doesn't init this reg to 0 like a real machine, force scroll reg to 0.

coco3: reset vert scroll reg on boot.

---

Kernel/platform-coco3/coco3.s
Kernel/platform-coco3/config.h
Kernel/platform-coco3/fuzix.link
Kernel/platform-coco3/kernel.def
Kernel/platform-coco3/main.c

as lifted (again) from the dragon port.

CoCo3: use discard space for extra buffers

---

Kernel/platform-dragon-nx32/devtty.c
Kernel/platform-dragon-nx32/video.s

A couple of bugs I noticed while porting this code to coco3.
The endian fix not only allows C structure to be define normally, but also allows the bounds checking code (the other submitted fix) to work (it treats the passed structure as an array of uint16's

Dragon-nx32 graphics fixes

---

Build/platforms/msp430fr5969.ld.h
Kernel/platform-msp430fr5969/config.h
Kernel/platform-msp430fr5969/crt0.S
Kernel/platform-msp430fr5969/externs.h
Kernel/platform-msp430fr5969/main.c
Kernel/platform-msp430fr5969/msp430fr5969.ld
Kernel/platform-msp430fr5969/tricks.S

As discussed. This gives me about 2kB of extra user space, as well as enough slack for another slot in the process table (because user space needs to change in 0x200 byte increments). Doesn't seem much, but that's 10% more user RAM.
Copying 2kB at one byte per 8 cycles on a 8MHz device takes 2ms. There are faster memcpys if necessary (it's got a rather nice DMA engine). But I don't think anyone will notice.
It's a shame syscall_fs has to be in common. That would give me another kilobyte...
I am, however, concerned it's rather brittle. If anyone moves a syscall, or adds a new one, my code will load the wrong overlay and Bad Things will happen. And because this will happen on an individual syscall level, nobody will notice until that syscall is exercised.

MSP430 overlay support

---

Kernel/platform-coco3/video.c
Kernel/vt.c

1. Fixes closing parens in vt.c.
2. Fixes coco3 platform's color code

coco3: color video debugging

---

Build/platforms/msp430fr5969.ld.h
Kernel/filesys.c
Kernel/include/kernel.h
Kernel/inode.c
Kernel/platform-msp430fr5969/build.mk
Kernel/platform-msp430fr5969/externs.h
Kernel/platform-msp430fr5969/main.c
Kernel/platform-msp430fr5969/msp430fr5969.ld
Kernel/platform-msp430fr5969/tricks.S
Kernel/process.c
Kernel/syscall_fs.c
Kernel/syscall_other.c
Kernel/tools/build.mk
Makefile

This uses your new tool to figure out which syscalls are in which file; thanks!
All syscall banks can now be used as overlays. Turns out that caching a process' current overlay in udata.u_page2 is unnecessary --- I can figure out which overlay was loaded after switchin by looking at the syscall in udata.u_callno, and I already have code to do that. Total amount of extra code: one subroutine call in switchin. I now have a 27kB userland, which is actually getting quite respectable. (That's about the same amount free as a BBC Micro with tape filesystem and mode 7.)
However, I did have to move unlinki and the guts of _sync into common code, as these functions are called from multiple syscall banks and we don't support cross-bank function calls. (How did this work on hardware banked …

Better MSP430 overlay support

---

.travis.yml
Library/libs/strcpy.c

This fixes the Travis setup so that it builds again, at least for 6502test, trs80 and msp430. (dragon is still broken.) It also reworks it into a proper build matrix so that all platforms get built simultaneously --- this prevents embarrassment when, e.g., TI move the MSP430 toolchain and suddenly nothing works any more.

Fix Travis setup

---

Kernel/tty.c

A couple of bugs fixes found in tty.c?
- the DEAD flag gets checked so early, that any data still in the buffer after a carrier drop cannot be retreived.
- Opening a tty with NBLOCK wasn't keeping the number of users updated... causing weirdness when closing the port - the t->users count would wrap to -1 on close, and the low-level driver closer (actually needed for drivewire) wasn't being called.

Couple of tty.c fixes?

---

Kernel/include/kernel.h
Kernel/syscall_proc.c

I suspect I'm the only one to have noticed this because p_priority normally stores a small integer, which points at a memory location which is usually unused. I noticed this on the ARM because of unalignment traps. I should probably try and get zero page unmapped --- need to look into how to relocate the reset vectors...

Data corruption in waitpid()

---

Applications/V7/games/wump.c
Applications/util/init.c
Kernel/include/kernel.h
Kernel/include/userstructs.h
Kernel/syscall_fs.c
Library/include/sys/types.h
Library/include/syscalls.h
Library/libs/error.c
Library/libs/free.c
Library/libs/malloc-l.h
Library/libs/malloc.c

The only bit of any great interest is the stcpy(), which writes to the user's struct _uzistat structure. I've rearranged it to avoid random member padding upsetting it due to alignment, but I'm not really a fan --- it's very fragile, and any changes would probably fail. I'd much rather import struct _uzistat into the kernel and copy the members one by one, but on small architectures that's probably very expensive.
I suspect the other structures will fail in the same way, but I haven't been bitten by those yet.

Fix alignment and sizing issues

---

Kernel/platform-msx2/image.mk

bootrom.bin is generated along with fuzix.ihx

msx2: fix build dependency

---

Applications/util/kill.c

This bug made every signal number into SIGKILL, disallowing TERM or numbered sigs.

kill.c: bugfix: inverted test of strcmp

---

Kernel/syscall_exec16.c

fixes bug in core-dumping that caused 0 length core files.  See issue #320.

coredump: clear u_error for new batch of calls.

---

Library/libs/opendir_r.c

On first call to readdir() after opendir_r(), readdir returns garbage, thinking it's internal directory file buffer is full and unprocessed.  If the DIR is user-allocated on stack, then there are no guarantees they are set to anything.  
https://github.com/EtchedPixels/FUZIX/blob/master/Library/libs/readdir.c#L14
dnext(), called by readdir(), tests next and last with nothing setting them.

opendir_r: bugfix: bad first iteration of readdir

---

Applications/util/umount.c

bug: umount not re-writing /etc/mtab correctly.  In rm_mtab():  strtok is used to find the umounted device line, but strtok modifies it's input string, so non matching entries where being truncated (by strtok).  Cleaned up formatting.

bugfix: umount

---

Kernel/platform-coco3/video.c

added a "reverse" memmove, an overlapping copy from high memory down.  This correctly make video.c scroll down correctly and "vi" works a touch better.

coco3: fix scroll_down().

---

Applications/util/fforth.c

Turns out that one row of the table is only 24 bytes when it's on my amd64 machine.
I would ask how this ever worked, but it apparently didn't.

Don't hardcode the cell size when calculating offsets into the interpreter table.

---

Kernel/platform-coco3/main.c

Not only was I overwriting a byte in every page in the kernel, scanning every 8k page in memory was stupid anyway.

coco3: 2M bug: don't scan(aka overwrite) kernel memory.

---

Library/include/sys/.gitignore
Library/include/termcap.h
Library/libs/tzset.c

In termcap.h there was an extra closing brace on tputs
In tzset.c there was a VOID that caused unhappiness; changed to void. Also expunged DOS line endings and trailing whitespace.
Now builds and apparently working on 6809.

Tweaks to allow library to build on 6809

---

Kernel/platform-coco3/video.c
Kernel/platform-dragon-nx32/devtty.c

we really can write 32 byte wide lines, 192 line columns

Fix dragon, coco3 graphics bounds checking

---

Kernel/platform-coco3/README

Add some notes as discovered while this newcomer first tried
to build the Coco3 FUZIX target and boott it on (Linux) MAME.

Addition docs for Coco3 target build/boot on MAME

---

Applications/SmallC/.gitignore
Applications/SmallC/primary.c

Regression, as noted in issue 377.  Function calls mis-parsed as syntax error.
Added enough code to go back to parsing them.

Issue 377: broken calling of function in expressions

---

Kernel/dev/devdw.c
Kernel/lowlevel-6809.s

This needs some optimization (what's the easiest way to propagate the sign bit when optimizing?).  ashrsi3 follows same calling convention as existing ashlsi3.  This makes new devio changes compile on 6809.  Plus simple bug fix for devdw.

Add a schlocky ashrsi3 to 6809, fix devdw.

---

Kernel/platform-multicomp09/config.h
Kernel/platform-multicomp09/sdc.s

thanks to Brett's fix to the common interrupt code.
Multicomp09 shown working on both emulation and FPGA.

Switch multicomp09 away from legacy exec model

---

Library/include/math.h

and delete trailing whitespace, for fun.

Fix apparent typos that caused gcc-6809 to barf.

---

Applications/util/touch.c

Following usual tool behavior, touch should emit an error when it can not
create a file (for instance, due to permissions).  Error message used mimics
touch as found on your typica *-ix system.
Shuffled error treatment, as close(create(...)) obscures the actual errno with
"invalid file descriptor" errno.

Have touch emit error message

---

.gitignore
Kernel/.gitignore
Kernel/Makefile
Kernel/cpu-z80/image.mk
Kernel/dev/net/net_z80pack.c
Kernel/platform-zx128/bank128.c
Kernel/platform-zx128/config.h
Kernel/platform-zx128/devfd.c
Kernel/platform-zx128/devices.c
Kernel/platform-zx128/devmdv.c
Kernel/platform-zx128/disciple.h
Kernel/platform-zx128/fuzix.lnk
Kernel/platform-zx128/main.c
Kernel/tools/.gitignore

Main change is isolation of the microdrive swap support inside the "ifdef SWAPDEV" blocks. zx128 use old swapping mechanism and so cannot be compiled now.
Also little changes in gitignores/makefiles and accidental fix for net_z80pack.c

Making zx128 port compilable

---

Build/platforms/zx128.mk
Kernel/platform-zx128/Makefile
Kernel/platform-zx128/betadisk.c
Kernel/platform-zx128/betadisk.h
Kernel/platform-zx128/betadisk_internal.s
Kernel/platform-zx128/config.h
Kernel/platform-zx128/devices.c
Kernel/platform-zx128/fuzix.lnk

Betadisk-128 is possibly the most popular ZX Spectrum floppy controller in the world (taking into account its huge popularity in the Eastern Europe). But it hardly can be used directly because WD1793 (which it is based on) ports are only available from the TR-DOS ROM. 
But while implementation of "true" driver is tricky, the simple primitives for the heads positioning or 256 bytes sectors read/write may be executed from that ROM using simple hacks.
Bad thing here is that these hacks depend on TR-DOS firmware version. Currently everything is made for the 5.03, which is most widespread in ex-USSR (and seems to be the latest official version released by Techology Research Ltd). For other versions or earlier Betadisk-48 controller some more generic solution is needed.

zx128: Betadisk-128 driver and filesystem building definition

---

Library/libs/Makefile.6809

found this issue when trying to ranlib libm6809.a: 'error: multiple defined label _fp_scan'

found this issue when trying to ranlib libm6809.a

---

Library/libs/Makefile.6809

ar: missing operation letter, in this case 'r', must have one

added missing operation letter

---

Kernel/dev/net/net_native.c
Kernel/include/net_native.h

also adds some prototypes so syscall_net.c can find 'em.

net_native: add async event for remote shutdown.

---

Applications/util/uname.c

When I removed calls to printf/fprintf to save memory, I forgot to change where usage() goes.
This commit fix this issue.

usage now outputs to stderr

---

Applications/util/which.c

re-idented/formatted
defaults to "/bin" instead of "." if PATH is not set
use snprintf instead of strcpy, safer
stop spewing error message to stdout
returns success only if all the executables have been found

refactored which utility

---

Applications/util/fuzix-util.pkg

This was reported by Ron Klein while compiling for a CoCo.  Maybe if-cpu is broken?

util: patchcpm no longer exists to install

---

Kernel/cpu-6809/cpu.h

There is a reason why size_t was signed ?

fixed compile error: added ssize_t, changed size_t to unsigned

---

Kernel/platform-coco3/main.c

Fixes a minor bug during boot that messes with credit to Mr. Nitschke :)

coco3: init bug: skip scanning screen memory

---

Kernel/platform-coco3/coco3.s

This seems to be much simpler than actual banking.  This is a work-around to let us use kernel cpu space 0xc000-0xe000,  which was donated by kernel to help in pseduo-forking init.

coco3: shuffle memory to let us actually use kernel memory past 0xc000

---

Kernel/platform-coco3/devtty.h

Not sure how I missed this too...*sigh*

coco3: define KEY_ROWS to compile vt ioctls

---

Kernel/platform-coco3/ttydw.c

A patch from Michael Furman.  Backs off dw polling as tty buffers fill up.  Better more efficient through-put. Thanks Michael.  I suggest this be implemented by all platforms doing drivewire.

coco3: drivewire: dynamic polling back-off.

---

Applications/netd/lwwire.c

to match recent commits in the lwwire project

coco3: make netd device module talk proper lwwire

---

Kernel/platform-coco3/devices.c
Kernel/platform-coco3/dwtime.c
Kernel/platform-coco3/libc.c
Kernel/platform-coco3/main.c
Kernel/platform-coco3/ttydw.c
Kernel/platform-coco3/ttydw.h

* Stores the probulated drivewire server type
* Adds platform param "NODW" to disable drivewire probing.
* found more stuff that should be in discard

coco3: better/conditional initialization of drivewire

---

Applications/levee/.gitignore
Applications/levee/Makefile
Applications/levee/display.c
Applications/levee/fuzix-levee.pkg
Applications/levee/levee.h
Applications/levee/termcap.i

The termcap version needs work still, should load from /etc/termcap rather than $TERMCAP.

Applications: levee: Build versions for ansi, vt52 and termcap

---

Kernel/dev/devfd.c
Kernel/dev/devfd_hw.s
Kernel/platform-p112/p112.s

The driver would previously not work below about 10MHz.
Tested on zeta-v2 (Z80) at 6MHz, 8MHz, 10MHz, 18.432MHz and 20MHz.
Tested on p112 (Z180) at 16MHz.
This change also increases the maximum number of times a floppy
operation will be retried before we fail it. It also no longer panics on
floppy errors.

Kernel: devfd: Optimisations for reliable operation on 6MHz Z80

---

Kernel/dev/net/net_native.c
Kernel/include/kdata.h
Kernel/kdata.c
Kernel/platform-coco3/Makefile
Kernel/platform-coco3/config.h

This hopefully will make it easier to try native networking on lesser machines without the overhead of level 2 code.

Allow for networking w/o level 2

---

Kernel/bank16k.c
Kernel/include/kernel.h
Kernel/swap.c

bank16k platforms wishing to swap will have to provide a copy_common( uint8_t pageno ), and do something like this in switchin():
```
call _get_common    ;   to get a usable common page
fix up platform-specific mmu and switch to new common
call _swap_finish   ;  to swap in the rest of the swapped out task
```

bank16k: add swapping

---

Kernel/syscall_exec16.c

This experiment seems to let me load and run binaries based off the progload address found in the binary header, rather than a static address.  This allow me to load and run bins from stock dragon/coco2 root images. I wanted to redefine PROGLOAD, but unfortunately, "start.c" uses this #define to a great extent.  It seems a redefined macro for PROGLOAD would have to be pretty smart for both usages.

exec(): take PROGLOAD from the binary header

---

Kernel/platform-coco3/Makefile
Kernel/platform-coco3/README
Kernel/platform-coco3/devices.c
Kernel/platform-coco3/devlpr.c
Kernel/platform-coco3/devlpr.h

Add /dev/lpr for Drivewire Printer, for now.

coco3: add /dev/lpr

---

Kernel/dev/net/net_native.c

"sd" doesn't exist: get it from "s"

net_native: a slight addition

---

Kernel/platform-coco3/coco3.s
Kernel/platform-coco3/ide.s

low level ide routines where trying to use blk_op struct after flipping them out of memory map (via rawflag=1).  Also: coco3 blkdev memory helpers where not in common.

coco3: fix blkdev mapper routines: blk_op is not in common.

---

Kernel/filesys.c
Kernel/platform-coco3/Makefile
Kernel/platform-coco3/config.h
Kernel/platform-coco3/devices.c
Kernel/platform-coco3/drivewire.s

This will let me have special builds tailored for each major coco3 platforms: real, emulated, fpga, and the fppa nano.   Each can have their own driver matrix.

coco3: make different coco3 platforms

---

Kernel/devsys.c
Kernel/syscall_fs2.c

'ps' was failing, due to a 0 return on read.  uput only returns 0 or -1, not number of bytes.

devsys: read should return no. of bytes

---

Kernel/syscall_exec16.c

new simpler exec() wasn't putting the hdr into userspace.

kernel: syscall_16: put header in userspace too.

---

Applications/util/fuzix-util.pkg

gives us some sane way to control reboot on really fast machines.

util: link 'halt' to 'reboot' on fs

---

Kernel/bank16k.c
Kernel/bank16k_low.c

pfptr goes down as memory is allocated. return it's compliement instead.

bank16k: report correct memory used

---

Applications/netd/coconic.c
Applications/netd/device.h
Applications/netd/lwwire.c
Applications/netd/slip.c

all the pendanticy of gcc didn't catch that has_arp was global, but I guess including the header in the device driver helps.  Also fix lwwire.c returned -1 when there's not an error.  Still needs some debugging in set_timer(), as this call mysteriously kills netd daemon.

Fix a few new bugs in netd

---

Applications/util/init.c

init was adding bits to runlevel mask in crunched table without starting it at zero.  rarely resulting in a matching entry when cleaning up.  Also fix "group kill procs in this run level, that are not in new runlevel" syntax error.

init: crunched table not reseting runlevel mask, correct cleanup.

---

Applications/netd/dig.c
Applications/netd/gethostbyname.c
Applications/netd/netd.c

"user_request" flag does nothing in the UDP handling, and UDP doesn't need any complicated closing anyway, so release and free up UDP struct ASAP after kernel's close().

Quick fixes for netd

---

Applications/netd/netd.c
Applications/netd/uip.c
Applications/netd/uip.h

as per issue #555
"uIP needs tweaking so that it uses the bind() provided local socket if presetn when we connect()."
if we pass a local port of 0 to uip, it'll choose the local port, else it'll use fuzix's idea of the port no.  is there a reason even to bother with uip picking it's local port?

netd: let Fuzix choose local port

---

Kernel/process.c

This bug was causing chksig to return weird signal nos... crashing (my) system.

signals: fix precedence to report correct signal no.

---

Kernel/platform-coco3/devtty.c
Kernel/platform-coco3/devtty.h
Kernel/platform-coco3/main.c

Because life with a NTSC T.V. at 80 columns sucks.

coco3: take cmd line for default video mode

---

Applications/games/fortune-gen.c

This bug was sending incorrect return values back to sh.

fortune: bug: main doesn't return success.

---

Kernel/platform-coco3/coco3.s

Don't trust our boot environment to correctly set this SAM register.

coco3: poke RAM mode on init, just in case.

---

Applications/util/cal.c

'cal' was trying to use the wrong memset() prototype, causing the the 3rd column of a yearly dump of months to disappear.

util: 'cal' fix output.

---

Kernel/dev/net/net_native.c

recent udata.u_count changes broke net_native - socket reads/writes always returned 0.  Calls to readi/writei the backing file now reset u_count so switch over to using u_done, instead.

net native: u_count is reset after calls to readi/writei now.

---

Kernel/platform-coco3/Makefile
Kernel/platform-coco3/config.h
Kernel/platform-coco3/devices.c
Kernel/platform-coco3/sd.s

Implements the low level bits needed to use Kernel/dev/devsd on the CoCoFPGA's sd card.

coco3: implement sd card.

---

Library/libs/curses/setterm.c

VMIN and VEOF are unioned in FUZIX, so reset VMIN to 0 on raw(),
otherwise set it to EOF (4).  This makes raw() seem to behave better.

curses: tailor tty VMIN to FUZIX

---

Library/tools/syscall_6502.c

was trying to use an initialized index to array of syscall names. Caused a segfault on my machine.

lib: fix 6502 syscall generator

---

Kernel/dev/net/net_native.c

this prevents netdev_findevent() from continually reporting on a
dead socket, thus preventing any other socket/event from being
reported to the network daemon.

net_native: clear event upon unhooking.

---

Kernel/platform-amstradnc/bootblock.s
Kernel/platform-amstradnc/devfd.c
Kernel/platform-amstradnc/nc200/Makefile

Enabling raw disk I/O caused horrible crashes --- turned out I didn't realise that `d_blkoff()` modifies the udata variables. It works now, and is much, much faster.
I also found that the NC200 was suddenly failing to start 90% of the time, which eventually turned out to be because it was reading the resume vector from an umapped page and getting gibberish. I rewrote the bootblock code to be more consistent across both platforms. PCMCIA boot still doesn't work on the NC200, though.
Cowgol runs! About half way (taking approx. ten minutes) before hanging --- I think it's running out of memory.

Amstrad NC boot fixes, raw disk I/O fixes

---

Kernel/platform-coco3/devlpr.c

to fix a bug reported by Mikey https://github.com/n6il.

coco3: fix lp driver to return no of bytes written, not just 0

---

Applications/MWC/cmd/expr.y
Applications/MWC/cmd/find.y

The original versions of `expr.y` and `find.y` worked fine with `byacc` but not other versions of `bison/yacc`.  The issue is that _`byacc` emits code in a different order than other yaccs_ so it worked with byacc but not the others.  Fix is to move globals up to the "global declarations" section and now the output from various versions of bison/byacc/yacc all compile.
Reviewed by: @beretta42 (Brett Gordon)

Fix expr.y and find.y to work with regular yacc

---

Applications/games/Makefile.6809
Applications/games/fuzix-games.pkg

This compiled for gcc6809 straight-away, and plays online dat files quite nicely

6809: compile and add advsys interpreter to games package

---

Kernel/include/vt.h
Kernel/platform-coco3/devtty.c
Kernel/platform-coco3/devtty.h
Kernel/platform-coco3/video.c
Kernel/vt.c

This makes common vt code keep track of each vt's ink/paper.  Fixes bug where one terminal's escape codes changes colors on all others.

Fix vt color handling with multiple vts

---

Kernel/platform-coco3/devtty.c

The vt switcher structure has grown a few bytes recently, match up initial platform structures, give a reasonable color to the second vt. (kernel vt core sets first vt up for us)

coco3: give all terminals some reasonable default ink/paper colors

---

Applications/games/Makefile.z80

...
fortune: 2789 bytes from 256
ls -l adv01 adv02 adv03 adv04 adv05 adv06 adv07 adv08 adv09 adv10 adv11 adv12
adv13 adv14a adv14b myst01 myst02 myst03 myst04 myst05 myst06 myst07 myst0
8 myst09 myst10 myst11 fortune-gen startrek hamurabi cowsay advint fortune
qrun.cb >size.report
ls: cannot access 'qrun.cb': No such file or directory
Makefile.z80:37: recipe for target 'sizes' failed
make[2]: *** [sizes] Error 2
make[2]: Leaving directory '/home/flag/FUZIX/Applications/games'
Makefile:28: recipe for target 'games' failed
make[1]: *** [games] Error 2
make[1]: Leaving directory '/home/flag/FUZIX/Applications'
Makefile:61: recipe for target 'apps' failed
make: *** [apps] Error 2

games: fix compilation

---

Applications/util/init.c

I noticed 'more' was complaining when a user has no permission on it's own controlling tty.  linux does something like this, and it seems easy enough to add here.

init(getty): set/reset owner of tty on login

---

Applications/MWC/cmd/Makefile.z80
Applications/MWC/cmd/asz80/Makefile.z80
Applications/SmallC/Makefile.z80
Applications/V7/cmd/Makefile.z80
Applications/V7/cmd/sh/Makefile.z80
Applications/V7/games/Makefile.z80
Applications/as09/Makefile.z80
Applications/cursesgames/Makefile.z80
Applications/flashrom/Makefile.z80
Applications/games/Makefile.z80
Applications/ld09/Makefile.z80
Applications/ue/Makefile.z80
Applications/util/Makefile.z80
Library/libs/Makefile.z80
Makefile

One of the major slowdown in the z80 build is the O2 optimization level.
This pull request introduce a new global $FUZIX_CCOPTS variable that encapsulate the cc optimization level (and possibly other cc options), and is reused by all the z80 Makefiles down the road.
By default this pull request doesn't change the actual O2 level, but can that on the command line:
$ FUZIX_CCOPTS=-O0 make ...
On a sluggish Intel Atom c750 4 cores / 8 threads, make -j4 goes down from ~2hours to ~30 minutes.
On the Github / Google Cloud default instance for Travis CI (2 x 2.6Ghz Xeon with 7.5Gb of ram) i could rebuild the entire z80pack in less than 15 minutes, without any swap usage.
While not perfect (this pull only cover the z80 side of the build), it is mandatory for another feature that i would like to …

Z80 fuzix ccopts

---

.travis.yml

This pull request re-enable the Travis CI
It uses my Fuzix ppa[1] where i packaged a good sdcc snapshot (the revision that we discussed in this other bug[2]), the gcc6809 that was used historically and the latest cc65 release
At the moment i've enabled these builds:
z80: rc2014 trs80 and z80pack
mc6809: dragon-nx32
unfortunately i couldn't enable any 6502 based target since both the v65
and v65816 targets fail to build.
After pulling this, you should connect your Github account to Travis (https://travis-ci.org/), and in the Settings -> General section enable:
Build pushed branches
Build pushed pull requests
Auto cancel branch builds
Auto cancel pull requests build
and that's it - you can manually trigger a build at that point, or as soon as you push a new commit to your repo (or as soon …

travis: re-enable Travis CI

---

Applications/V7/cmd/Makefile.6809

This was causing 6809 build to fail looking for ed

6809: compile ed in V7

---

Applications/util/coco3.link
Kernel/platform-coco3/fuzix.link

I'll swear that I've fixed this problem before... guess not!

coco3: fix link script typo

---

Kernel/platform-coco2cart/devsdc.c

With this fix it boots again on the CoCo2 w/ SDC.

coco2cart: bug: sdc driver still not returning no of bytes read/writen

---

Kernel/platform-rc2014/fuzix.lnk

ppide_rbc.c has #ifdef CONFIG_PPIDE so we don't add useless code if PPIDE isn't configured

rc2014: fixed missing functions when ppide enabled

---

Kernel/platform-coco3/coco3.s
Kernel/platform-coco3/main.c
Kernel/platform-coco3/tricks.s
Kernel/platform-coco3/usermem_gime.s
Kernel/platform-coco3/videoll.s

This makes FUZIX work on CoCo3 with older DISTO style (non readable mmu) upgrades.

coco3: make work with older RAM upgrades

---

Kernel/platform-coco3/tricks.s

This stack blasting copier is 3.8 cycles per byte copied. The old code was 7.3 cycles per byte. This method could also be helpful in the dragon-mooh port @tormodvolden.

coco3: stack blast on mmu bank copies

---

Kernel/platform-coco3/devices.c
Kernel/platform-coco3/dwtime.c

kernel sets this from root superblock now, and we already have a
userspace app that can set the date from drivewire. Might as well
save a bit of kernelspace.

coco3: delete drivewire time setting code

---

Applications/util/vile.c

the old code still bombs out if loading a small file, as even after loading, "size" is still larger than int_max and doread() fails with EINVAL.

vile: fix read

---

Applications/dw/dw.c

* was double spacing
* was hanging as tty does not pay attention to drop of carrier unless told.
* bit flipping bug in setting ECHO.

drivewire: fix up the 'dw' utility

---

Kernel/include/tty.h

This looks to be supported. I don't see anymore that are left out, on the input flags anyway.

tty: turn on IGNCR support in kernel

---

.travis.yml
Library/libs/Makefile.6502

Trusty is EOL upstream, move to Xenial and while here:
-update sdcc to 3.9.2-trunk-r11322 (latest upstream)
-update cc65 to 2.18 (latest upstream)
-update gcc6809 to 4.6.4
In particular, after updating cc65 to 2.18, a couple of 'Duplicate external identifier' error popped up:
make[2]: Entering directory '/home/flag/fuzix_stuff/FUZIX/Applications/util'
cl65 -o tar -L../../Library/libs -C ../../Library/libs/ld65-v65c816.cfg ../../Library/libs/crt0_6502.o tar.o c6502.lib -m tar.map
ld65: Error: Duplicate external identifier: '_bzero'
and
make[2]: Entering directory '/home/flag/fuzix_stuff/FUZIX/Applications/MWC/cmd'
cl65 -o m4 -L../../../Library/libs -C ../../../Library/libs/ld65-v65c816.cfg ../../../Library/libs/crt0_6502.o m4.o c6502.lib -m m4.map
ld65: Error: Duplicate external …

Update Travis environment and toolchains

---

Kernel/platform-msx2/msx2.s

this appears to fix msx2 platform down to v0.3.1, it remains broken in
more recent versions.

msx2: add missing _udata

---

Applications/V7/cmd/Makefile.6809

Bring makefile fpr 6809 for V7/cmds up-to-date

6809: build 'clear', makefile up-to-date

---

Applications/V7/cmd/sh/Makefile.6809
Library/libs/crt0_6809.s

This commit fixes 6809 build, in issue #771 
gcc spits out some automagic text sections that weren't accounted for in the fuzix header for 6809.
cheers, brett

Fix 6809 build

---

Kernel/cpu-68000/rules.mk
Kernel/devio.c
Kernel/lowlevel-68000.S
Kernel/platform-atarist/Makefile
Kernel/platform-atarist/cartridge.S
Kernel/platform-atarist/cartridge.ld
Kernel/platform-atarist/libc.c
Kernel/platform-atarist/loader.S
Kernel/platform-atarist/p68000.S

A few minor updates were needed to start on the Atari ST using GCC 10.2.

Atari ST vt boot fixes

---

Kernel/platform-atarist/Makefile
Kernel/platform-atarist/cartridge.S
Kernel/platform-atarist/cartridge.ld

A cartridge image can be built with
```
$(CROSS_LD) --orphan-handling=error --discard-all		\
-nostdlib --no-relax --script=cartridge.ld		\
-o ../cartridge cartridge.o
```
and then started using the `--cartridge Kernel/cartridge` option to the Hatari emulator, which will boot it very quickly.

atarist: Add cartridge target for easy emulation

---

Kernel/dev/blkdev.c
Kernel/dev/blkdev.h
Kernel/filesys.c
Kernel/include/kernel.h
Kernel/swap.c

This adds an HDIO_TRIM ioctl to block devices which can be used to pass information about unused blocks to a flash driver. This is needed to make slow flash like the ESP8266's work (via an FTL). Blocks are trimmed by the filesystem when freed, and by the swapper when swapping in a process, as processes are only ever swapped in once and this ought to speed up swapping out.
It'd be possible to add support to devsd for this, issuing CMD38 commands to the card, but erasing's a bit more complex on SD cards and usually not necessary, so I haven't looked into doing that yet.

Add HDIO_TRIM for use with flash devices.

---

Kernel/tools/makejv3.c

JV3 unused sector records should be filled with 0xff.
This also fills in the last non-record byte to 0xff making the JV3 image writeable.
This is (somewhat) documented in: https://www.tim-mann.org/trs80/dskspec.html#:~:text=directory%20track%20instead.-,The%20JV3%20Format,headers%20and%20data%20can%20follow.
"If a sector header is not in use (free), its track and sector fields must contain 0xFF"

Fill unused sector records with 0xff

---

Library/tools/libclean

Helps bubble up one of the errors from #158 
I was experiencing the same problem (that the library was not being correctly detected) on Arch Linux because the actual binary is installed at `/sbin/sdcc` and `findsdcc` assumes that the libs can be found from a relative path.
Rather than trying to include packaging specific logic to `findsdcc`, I've added a simple check in `libclean` to hard fail if `LIBZ80` is not populated with a valid directory path and to instruct the user to manually set the variable to the correct path.
I've tested this code change by running `make` on my Arch install and having it fail, and then manually setting `LIBZ80` (before the check) and running again and it's now passing the check and continuing the build.

Make LIBZ80 autodetection error check

---

Applications/rules.armm0
Kernel/include/elf.h
Kernel/syscall_execelf32.c
Library/elfexe32.ld

By changing the linker script to bake information about the size of the BSS and where the relocations are into the ELF file, I can remove all the section header stuff from the loader, which simplifies things considerably.
However, GNU ld then behaves very oddly if I try to strip certain sections (including rearranging or removing program headers... I think it could be a bug). This means I have to be rather less aggressive there. This doesn't affect the amount of data in memory, but it does make the files on disk a bit bigger.

Simplify the ELF loader by quite a lot

---

Applications/util/Makefile.generic
Applications/util/blkdiscard.c
Kernel/dev/blkdev.c
Kernel/include/kernel.h
Kernel/platform-rpipico/README.md
Kernel/platform-rpipico/config.h
Kernel/platform-rpipico/devices.c
Kernel/platform-rpipico/rawflash.c
Kernel/platform-rpipico/update-flash.sh
Library/include/syscalls.h

This finally fixes the NAND flash code. It also adds a `BLKGETSIZE` ioctl to get the LBA size of a partition, fixes a bug in `HDIO_TRIM`, exports both to userland, and adds a userspace tool for erasing an entire partition.

Make the NAND flash work on the Pico

---

Kernel/include/flat.h
Kernel/syscall_exec32.c
Standalone/Makefile
Standalone/elf2flt.c

This turned out to be pretty simple, but it currently won't work: the kernel loader needs a fair bit of work as it's currently hard-coded for the 68000, and the tool needs to be taught about 68000 relocations anyway. Also, it appears that bFLT is limited to 32-bit relocations only. I don't know how this works with platforms like the PowerPC where 32-bit constants are traditionally inlined but split into two 16-bit fields in two 32-bit instructions.

Add prototype of a standalone tool for making bFLT files from static PIE elf files.

---

Kernel/platform-trs80/trs80-bank.s

Bit 7 of $84 is the video page bit.  Unintuitively it specifies which page is second.  In normal operation it is set to 1 so that when video memory is mapped to $F800 you have page 0 at $F800 and page 1 at $FC00.
This change has been verified on a real machine.  It makes no difference on xtrs which is a bug in its emulation.
The boot block sets the high bit of $84 so no change is needed there.

Have video memory be linear

---

Kernel/syscall_fs.c

This fixes the issue where pipe() assumes its parameter to be a `int16_t*`, causing pipes not to work on 32-bit systems.
See: #832

Fix pipe() on 32-bit systems.

---

.travis.yml

Focal is the latest LTS Ubuntu release (supported up to April 2025), while Xenial, our current CI base OS, is about to to EOL in ~1 month (April 2021).

travis: bump CI to Focal

---

Kernel/platform-dk-tm4c129x/ssi.c

Thanks to this, at least partitions are found on the MMC card. Sadly, /init cannot be loaded. I suspect much has changed in the ELF loader.

dk-tm4c129x: ssi: correct some of the constant values

---

Standalone/elf2flt.c

armm4 Makefiles use `-fpie -DPIE` flags, this results in creation of position independent executables, their type is not ET_EXEC but ET_DYN.

compatibility: allow position independed executables too

---

Kernel/cpu-armm0/cpu.h
Kernel/syscall_exec32.c

We're almost there with running FUZIX on dk-tm4c129x!
Now it looks like that:
```
FUZIX version 0.4pre1
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2021 Alan Cox <alan@etchedpixels.co.uk>
Devboot
256kB total RAM, 256kB available to processes (15 processes max)
Enabling interrupts ... ok.
SD drive 0: hda: hda1
bootdev: hda1
Mounting root fs (root_dev=1, ro): OK
Starting /init
init version 0.9.0ac#1
/etc/rc: Unknown error 1113915252
^ ^
n n   Fuzix 0.3.1
>@<
Welcome to Fuzix
m m
login: root
login: unable to change owner of controlling tty
Welcome to FUZIX.
```
I wonder whatever happened to `/etc/rc`...

compatibility: fix exec issue with 32-bit little-endian architectures

---

Kernel/platform-dk-tm4c129x/syscall.c
Kernel/syscall_exec32.c
Makefile

This set of patches addresses the regression in ability to work with old 'working' rootfs images. Sadly, the most recently created rootfs image still does not work.
Booting with the old image:
```
FUZIX version 0.4pre1
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2021 Alan Cox <alan@etchedpixels.co.uk>
Devboot
256kB total RAM, 256kB available to processes (15 processes max)
Enabling interrupts ... ok.
SD drive 0: hda: hda1
bootdev: hda1
Mounting root fs (root_dev=1, ro): OK
Starting /init
init version 0.9.0ac#1
Checking root file system.
Current date is Wed 2021-05-12
Enter new date:
Current time is 23:02:35
Enter …
```

Fix regression in 32-bit exec

---

Applications/rules.armm4
Standalone/elf2flt.c

With the original hack:
```
reloc: 0 entries
Writing 0 relocations.
```
After modifying the hack:
```
reloc: 108 entries
Writing 108 relocations.
```
Finally, rootfs is usable!
```
FUZIX version 0.4pre1
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2021 Alan Cox <alan@etchedpixels.co.uk>
Devboot
256kB total RAM, 256kB available to processes (15 processes max)
Enabling interrupts ... ok.
SD drive 0: hda: hda1
bootdev: hda1
Mounting root fs (root_dev=1, ro): OK
Starting /init
init version 0.9.0ac#1
Checking root file system.
Current date is Sat 2021-09-04
Enter new date:
Current time is 13:15:47
Enter new time:
^ ^
n n …
```

armm4: fix the hack that prevents relocations from being written for ARM targets

---

Kernel/cpu-armm4/cpu.h
Kernel/platform-dk-tm4c129x/eth.c
Kernel/platform-dk-tm4c129x/interrupt.h
Kernel/platform-dk-tm4c129x/tm4c129x.h

This is still very far from being usable, but at least some
signs of life can be observed: once breakpoint is set on eth_isr()
in the debugger, one can 'ping' this device's hw address (e.g.
using macping.sh script) and the breakpoint on the IRQ handler
should be hit.
The `macping.sh` script I'm using is:
```
#!/bin/bash
network=192.168.1.1/24
if [ "$#" -ne 1 ]; then echo Usage example: $0 aa:bb:cc:dd:ee:ff; exit 2; fi;
nmap -sP $network >& /dev/null
ip=$(arp -n | grep $1 | awk ' { print $1 }')
ping $ip -n -q -c 2 -i 0.2 -w 1 >& /dev/null
if [ $? -eq 0 ]; then
echo Device is online \($ip\)
else
echo Device is offline
exit 1
fi;
```
you need to change the `network` variable to the address space used in your home network.

dk-tm4c129x: WIP: let's blink some lights on the network device

---

.github/workflows/c-cpp.yml

Use the internal GitHub actions to implement a simple CI pipeline (identical to what we had with Travis before) but:
1) actions are handled internally of GitHub, no need to mess around with silly sync tools that suddenly stops to work
2) it's way way faster than Travis
3) use upstream Linux m68k cross toolchain (m68k-linux-) for 68 builds

Switch to GitHub CI actions

---

.github/workflows/continuous-integration.yml

Stop cut&pasting pieces of code around, and switch to a build matrix - this should make the entire process easier to reuse and push forward.
And while here, give the file and action a more sensible name.

Streamline CI and switch to a build matrix

---

Kernel/dev/net/net_w5x00.c

Fix sbcv2 build, with this one the entire CI pipeline is finally green.

w5x00: fix build failure caused by missing cast

---

.github/workflows/continuous-integration.yml

Fix a cut&paste error, and install the correct arm toolchain instead.

.github/workflows: ci: armm0-libc: install the correct toolchain

---

Applications/netd/fuzix-netd.pkg
Kernel/platform-dk-tm4c129x/eth.c

Three things were wrong:
- 'if' that was always true and was never needed blocked
all of the outgoing traffic
- outgoing buffers were never freed
- /dev/eth was a block device while it should have been
a character device
ICMP pings are now coming back from the device!

dk-tm4c129x: fixes in the ethernet driver

---

Library/include/proc.h

With this patch it is finally possible to see the process
name on the arm-based devices.

arm: fix huge instability in reading the process data from userspace

---

Applications/netd/Makefile.armm4
Applications/netd/netd.c
Applications/rules.armm4
Kernel/cpu-armm4/rules.mk
Kernel/dev/net/net_native.c
Kernel/include/net_native.h
Kernel/syscall_net.c
Library/include/sys/net_native.h

As connect() was never terminating, I looked at it and found several problems. Now connections are established and data can be transferred. Also emitting ICMP packets is fixed now so the remote hosts can be finally pinged.
A huge benefit from implementing in-memory ringbuf: netd-eth can now be started on read-only filesystems. The number of available sockets had to be halved though. Normally, 64k buffer would have to be allocated. Turned out, malloc() crashed for allocations larger than 4k, and a binary with a buffer larger than 32k in data segment cannot be loaded (it says it's too big to load).
Some issues are still remaining, for example:
1. httpd - listen() does not seem to work
2. ping `req=` shows suspicious values
3. telnet prints some trash after connecting to remote hosts; yet it …

network: several changes that finally made it possible to connect to remote hosts

---

Kernel/cpu-armm0/cpu.h
Kernel/include/elf.h
Kernel/malloc.c
Kernel/platform-rpipico/CMakeLists.txt
Kernel/platform-rpipico/config.h
Kernel/platform-rpipico/tricks.S
Kernel/platform-rpipico/usermem.c
Kernel/syscall_exec.c
Kernel/syscall_execelf32.c

There was a pile of small issues which were preventing the Pico port from building. The biggest one (apart from the new source files) is the change in configuration in the USERMEM macros. I couldn't find a standard setting which worked --- `CONFIG_USERMEM_DIRECT` now only works on systems with no memory alignment requirements --- so I thought it simplest just to do a platform-specific `usermem.c`.
This now successfully boots an old userland I had lying around. It does not boot a current userland. I'll investigate that and try and find out what's wrong in another PR.
It also fixes some warnings.

Fix some accumulated bitrot on the rpipico port.

---

Applications/V7/cmd/sh/blok.c

I'd like to try this again --- it's needed for any platform with stack-below-heap, such as the Pico. This is useful for making minimal process sizes work, which is needed on the Pico to let it run swapless. (I'm also looking at doing this on the ESP8266, but that's more difficult due to the exotic memory layout.)
I remember you saying that you reverted it due to this breaking some of the other platforms. I've tried this change on the Z80 (the trs80 platform) and it seemed fine there, so I'm wondering whether the problem was something else. Do you recall any specific platforms that were broken that I should try with?

Try rolling forward the change needed for stack-below-heap again.

---

Kernel/platform-esp32/Makefile

Espressif changed something in their SDK --- turned a macro into a function --- which requires a little more work at our end. Everything worked on my system because I never got round to pulling the new version from git.
This doesn't actually change anything in the ESP32 build, but does fix the persistent build failure in CI.

Fix the ESP32 build.

---

Kernel/platform-pz1/devtty.c
Kernel/platform-pz1/main.c
Kernel/platform-pz1/ports.def
Kernel/platform-pz1/ports.h
Kernel/platform-pz1/pz1.s
Kernel/platform-pz1/tricks.s

These fixes and the latest addition to the pull request in RC2014 belong together to form the almost proper PZ1 emulation and real HW Fuzix environment.

Cleaned up I/O-ports. 512KiB RAM, no ROM.

---

Kernel/dev/devfd_hw-banked.s
Kernel/dev/devfd_hw.s

When _devfd_init is called, GetPrm stores the drive table pointer in IY.
Eventually, Motor is called via Recal -> FdCmd -> Motor. All along it is assumed that IY is unchanged.
Within Motor, external function _plt_idle is called. For platform-rc2014, at least, the first thing that _plt_idle does is change IY to #_timer_source.
_devfd_init writes the value 1 to (IY) but coincidentally #_timer_source is often set to 1 so this bug does not cause crashes in most systems.

Pointer reassignment bug in floppy driver

---

Kernel/platform-rc2014/discard.c
Kernel/platform-rc2014/main.c

Previously "rtcsec" in timer.c was not being initialized causing an incorrect first slide in updatetod().

DS12885: Fix startup inaccuracy

---

Kernel/platform-rpipico/main.c

I found it hard to tell if the RPI Pico was on or not. This pull request turns on the power led as a indication that the board has power and has started to boot.

added power indication led

---

Kernel/platform-sc111/discard.c

CCR bit 8 needs to be set to switch the clock divider off according to the documentation. Verified by measuring PHI output frequency.
Z8S180-K has no clock doubler and CMR bit 8 is always 1. With that, try to detect missing clock doubler and print the clock frequency accordingly.
Before adding this fix, the clock speed was reduced to 9.2 MHz on my REV K Z180 and the serial port did run with 57600 bit/s instead of 115200. On a Z180 REV N with clock doubler, there may be a similar effect after adding this patch, it may speed up to 230400 bit/s. Just something to keep in mind when there's garbage on the serial port. I don't have a REV N to test with.

Fix clock divider and print actual clock frequency on SC111

---

Kernel/platform-sc111/discard.c

By default, CONFIG_RTC_DS1302 is not defined for SC111, resulting in undefined reference to ds1302_init.

sc111: fix undefined reference to ds1302_init

---

Kernel/platform-sc111/Makefile
Kernel/platform-sc111/boot-romwbw.s

This adds a loader for RomWBW based on the SC126 code. In contrast to the SC126 loader, it loads the kernel from disk offset 0x3000, same as the SCM loader. This allows to create a single disk image that works for both SCM and RomWBW.
The second commit adds a rule to create a combined disk image. The disk image rule also adds a boot command string at offset 0x17c pointing to hda1, so that the boot device does not have to be typed during boot.
The RomWBW loader contains code that will switch the I/O port base to Z180_IO_BASE before starting Fuzix. That code expects the RomWBW I/O base to be 0xc0. On my fairly new SC111 system that is the case. According to my limited research, older RomWBW versions did also use 0xc0 on SC111. The I/O base values will be printed during boot like this: …

SC111: Add RomWBW loader and disk image

---

Kernel/platform-sc126/main.c

CONFIG_NET_W5X00 isn't defined and no data flow is possible without polling.
Fix this by checking if CONFIG_NET_WIZNET is defined instead like on other platforms.

sc126: fix wiznet polling

---

Kernel/platform-sc111/config.h
Kernel/platform-sc111/kernel.def

This primarily affects the SCM Fuzix loader, as it needs to know the current I/O base in order to work correctly. If there is a mismatch, Fuzix won't boot without any output on serial console.
With version 1.3.0 (2022-02-28), SCM switched from I/O base 0x40 to 0xC0. This change will make the SCM loader work on newer systems. Systems with SCM older than 1.3.0 will need this change reverted.
The RomWBW loader is not affected as RomWBW did always use I/O base 0xC0 on SC111 and the loader uses that knowledge to switch the I/O base if needed.

sc111: switch I/O base to 0xC0

---

Kernel/platform-sc111/devtty.c

This fixes a bug seen on Z8S180-K. When using GTKterm to paste a few characters to the serial port, the Fuzix system became unusable. Input data was still being processed and echo'ed back, but the wait pointer of the shell process got cleared and the tty driver would not deliver input data anymore. On further debugging, it turned out that the ASCI interrupt would trigger continuously with OVRN set and RDRF cleared when this happened.
Clearing errors by writing to EFR before exiting from the interrupt handler fixes the problem. According to the Z8S180 errata, clearing error flags might be a good idea on other CPU variants as well to prevent ASCI from stopping input processing after overrun.

sc111: clear ASCI error flags after reading input characters

---

Kernel/platform-n8/devtty.c
Kernel/platform-rc2014/devtty.c
Kernel/platform-rhyophyre/devtty.c
Kernel/platform-sc111/devtty.c
Kernel/platform-sc126/devtty.c
Kernel/platform-scrumpel/devtty.c
Kernel/platform-z180itx/devtty.c

Bit 2 is one of the speed select bits instead of parity.
I could only test this on SC111, but some other platforms look sufficiently similar, so applying the fix there as well.

devtty: ASCI odd parity flag is bit 4, not value 4

---

Kernel/platform-sc111/main.c

To reset the timer interrupt, read TCR first and then TMDR0L. Otherwise, on Z8S180-K the timer interrupt triggers with double of the intended frequency.

sc111: fix PRT timer interrupt flag reset

---

Kernel/platform-dk-tm4c129x/Makefile

`LOBJ` are listed in `OBJS`, so there is no need to list `armrelocate.o` separately as it results in linker error:
```
Kernel/platform-dk-tm4c129x/../lib/armrelocate.c:10: multiple definition of `plt_relocate'; armrelocate.o:Kernel/platform-dk-tm4c129x/../lib/armrelocate.c:10: first defined here
```

dk-tm4c129x: fix linker error

---

Kernel/dev/vdp1.s
Kernel/platform-msx1/devices.c
Kernel/platform-msx1/devtty.c
Kernel/platform-msx2/Makefile
Kernel/platform-msx2/devtty.c
Kernel/platform-msx2/discard.c

Note that the branch could be read as improvisation too ;-)
- It turned out that on MSX1 the tenth seconds where applied twice hence slowing down key repeat to molasses.  Fixed.
- Then took the repeat values from actual machines as a norm (which are not so linearly dependent on VDP frequency).
- The self-repeating ctrl-<sth> was due to only checking for SHIFT as modifier, changed that to SHIFT, CTRL, GRPH and CODE.
- Also, repetition stops not only on keys down change but also on modifier change.  Fixed.
- The big mystery of missing keys was due to me pressing the next key before letting go of the previous one.  Changed code to accept any number of keys down, yet only retain the last one pressed.  This is not the same as having multiple new keys down in one scan.  That will now give the …

MSX kbd improv

---

.github/workflows/continuous-integration.yml

-Bump m68k-gcc to 13.10 (and fix rc2014-68008 and tiny68k build as a side effect)
-enable CI actions on every push/pull (thus letting people build test their code before preparing a pull-req)

.github/workflows: ci: bump m68k-gcc to 13.10 and enable ci on every push/pull-req

---

Kernel/platform-msx2/Makefile
Kernel/platform-msx2/boot.s

MSX2 disk image is now bootable (hence no bootrom needed anymore) - that is if used with MegaFlash without romdisk, as I haven't found a key combination which disables booting from romdisk, except in the recovery mode (key up during boot) F3 which erases the romdisk (a bit drastic) ...
Would you consider publishing this MSX2 bootable diskimage on fuzix.org?

msx2: make disk image bootable

---

Kernel/dev/blkdev.c
Kernel/dev/devsd.h
Kernel/dev/devsd_discard.c
Kernel/platform-msx2/Makefile
Kernel/platform-msx2/boot.s
Kernel/platform-msx2/config.h
Kernel/platform-msx2/devide_sunrise.c
Kernel/platform-msx2/devide_sunrise.h
Kernel/platform-msx2/devmegasd.c
Kernel/platform-msx2/discard.c
Kernel/platform-msx2/fuzix.lnk
Kernel/platform-msx2/msx2.s
Kernel/platform-msx2/rules.mk
Kernel/platform-msx2/sunrise.s

MSX2 now can also boot from Sunrise IDE (with or without ROM).  There is only room for one blkdev, so either SD or IDE.  However we can still include MegaSD for the integrated MegaRAM mapper, as the IDE drive is first probed.  I had to move the data of Kernel/dev/blkdev.c to COMMONMEM in MSX2 (hence the initializer).  It should not impact other platforms (verified MSX1).  I also had to enable RST peephole optimization, to arrive within a some 60 bytes of the 48K boundary.

msx2: integrate Sunrise IDE

---

Applications/dw/Makefile.common

Was doing a `platform-coco3` build from scratch and hit the following issue with `Applications/dw`:  
```
make[2]: Entering directory '/home/n6il/src/FUZIX/Applications/dw'
m6809-unknown-gcc -c -I/home/n6il/src/FUZIX/Library/include -I/home/n6il/src/FUZIX/Library/include/6809 -Os dwterm.c
/home/n6il/src/FUZIX/Library/link/ld6809 dwterm.o -o dwterm  -L/home/n6il/src/FUZIX/Library/libs -lc6809 -L/usr/lib/gcc/m6809-unknown/4.6.4/ -lgcc
...
+ m6809-unknown-ld dwterm.o -L/home/n6il/src/FUZIX/Library/libs -lc6809 -L/usr/lib/gcc/m6809-unknown/4.6.4/ -lgcc --oformat=raw -o dwterm.b1 --script=/home/n6il/src/FUZIX/Library/link/m6809.link -Map=dwterm.map
+ m6809-unknown-ld dwterm.o -L/home/n6il/src/FUZIX/Library/libs -lc6809 -L/usr/lib/gcc/m6809-unknown/4.6.4/ -lgcc --oformat=raw -o dwterm.b2 …
```

dw: Add crt0 so the dw apps link properly

---

Applications/dw/Makefile.z80

`make diskimage` for z80 target platforms complains about missing dwdate application, tested building for cromemco and zx+3.

Update Makefile.z80 for drivewire applications folder

---

Kernel/platform/platform-pz1/Makefile
Kernel/platform/platform-pz1/README
Kernel/platform/platform-pz1/config.h
Kernel/platform/platform-pz1/devhd.c
Kernel/platform/platform-pz1/devhd.h
Kernel/platform/platform-pz1/devices.c
Kernel/platform/platform-pz1/devtty.c
Kernel/platform/platform-pz1/main.c
Kernel/platform/platform-pz1/ports.def
Kernel/platform/platform-pz1/ports.h
Kernel/platform/platform-pz1/pz1.s
Kernel/platform/platform-pz1/tricks.s
Makefile

These are the latest changes for the PZ1 platform. There will be a corresponding EmulatorKit pull request.
24-bit LBA block-device implemented via tinydisk, swap still missing Renamed PORT_ to IO_, _IRQ_TIMER to _TIMER
Some formatting (tabs & spaces)
Makefile updates

PZ1: Blockdevice, names & formatting

---

Kernel/platform/platform-rpipico/misc.c
Kernel/platform/platform-rpipico/update-flash.sh

Couldn't make my pi pico to shutdown cleanly, so I did the following:
Updated /etc folder in the image.
Added killall, substroot, links to halt and shutdown.
Implemented proper reboot and halt.

rpipico: added proper reboot and halt support

---

Kernel/dev/tinyide_discard.c

In my case (SC111 with SC145 and CF), the device signals DRDY before BSY is 0, which leads to a timeout and failed disk detection. So wait for BSY to be 0 in addition to DRDY before submitting the identify command.

tinyide: fix IDE device detection on boot

---

Kernel/platform/platform-rpipico/README.md
Kernel/platform/platform-rpipico/config.h

rpipico: fixed default SD card configuration. updated documentation.

---

Applications/netd/fuzix-netd.pkg
Kernel/platform/platform-tm4c129x/devices.c

I've found it when looking into the `/dev` tree on dk-tm4c129x

netd: fix /dev/eth colliding with later introduced /dev/rd0

---

Tools/build-armm4

As long as the cross-compiler is in the PATH, there should be no complaints.

build: the toolchain can be installed anywhere, e.g. in the home directory

---

Tools/build-armm0

I was testing clean build from scratch `make TARGET=rpipico`.
Because I don't run debian (I think) I needed to fix up script that locates gcc. I believe it should still be backwards compatible.

armm0: support gcc installation that is not in /opt

---

Applications/netd/htget.c

Bug introduced when #548 was merged (first commit wasn't dropped) - remove the duplicate fix

Fix htget saving duplicate content

---

Kernel/dev/cpc/albireo.c
Kernel/dev/cpc/video.s
Kernel/platform/platform-cpc6128/README
Kernel/platform/platform-cpc6128/cpc6128.s
Kernel/platform/platform-cpc6128/cpcvideo.s
Kernel/platform/platform-zx+3/plt_ide.h

CPC6128: _plt_reboot bug fix, albireo transfer speed optimization and renaming of things inherited from zx+3 port.
ZX+3: put plt_ide.h in platform folder as build fails without it.

CPC6128 and ZX+3 fixes

---

Kernel/dev/net/net_w5x00.c
Kernel/network.c
Kernel/syscall_net.c

With these changes dig and echoping "work" on a w5500.
Still more fixes required, as echoping will work twice, on the 3rd invocation it seems to never return from the `_netcall-> run_sockfunc -> psleep_flags -> psleep` call when doing the recvfrom. Still working on understanding why this is.

wiznet w5x00 - further UDP fixes

---

Applications/util/Makefile.common
Applications/util/Makefile.generic
Applications/util/cu.1
Applications/util/cu.c
Applications/util/fuzix-util.pkg

<h2>NAME
<a name="NAME"></a>
</h2>
<p style="margin-left:9%; margin-top: 1em">cu - simple
serial console.</p>
<h2>SYNOPSIS
<a name="SYNOPSIS"></a>
</h2>
<p style="margin-left:9%; margin-top: 1em"><b>cu</b> -l
device [-s speed] [-E escape-character]</p>
<h2>DESCRIPTION
<a name="DESCRIPTION"></a>
</h2>
<p style="margin-left:9%; margin-top: 1em">Simple and
minimal terminal emulator program, to use with modems and
alike.</p>
<p style="margin-left:9%; margin-top: 1em">Just like other
terminal emulator progrms <b>cu</b> supports escape sequence
to execute a command in <b>cu</b> itself.</p>
<h2>OPTIONS
<a name="OPTIONS"></a>
</h2>
<p style="margin-left:9%; margin-top: 1em"><b>-l
device</b></p>
<p style="margin-left:18%;">Path to the character device.
<b>-E escape-character</b> Set alternate …

util: cu - micro serial console

---

Applications/util/cu.c
Applications/util/fuzix-util.pkg
Kernel/dev/cpc/video.s

About dos filesystem manipulation utilities, I tried dosdir with a FAT16 partition and got the error reserved != 1 error. @EtchedPixels do you know the right way to use this with a partition in the same disk as the root filesystem?

Links created for dosdir, doswrite and dosdel utils in filesystem image. Fix type mismatch compilation error on cu.c

---

Kernel/platform/platform-esp8266/Makefile
Kernel/platform/platform-esp8266/README.md
Kernel/platform/platform-esp8266/config.h
Kernel/platform/platform-esp8266/update-flash.sh

Dear @ermiah, @EtchedPixels,
This PR want to continue the work #1090 and now make fburn should works fine (it needs an additional call to ld to generate the segment headers, maybe there is a clever way to add them).
As I don't use anymore the SD card reader for the root filesystem, and as now fburn works fine, I've booted correctly without the panic in #1091. @ermiah would you mind to try to boot on the flash drive? (it requires to recompile the kernel ~~with a new option~~ after an updating config.h)
Best.

Permit fburn for esp8266

---

Kernel/platform/platform-rc2014/boot-romwbw.s

RomWBW version 3.4 changed the memory layout, putting the HBIOS working copy into RAM bank 0. To prevent the Fuzix loader from overwriting HBIOS, store data for bank 0 temporarily in bank 4. Copy bank 4 to bank 0 immediately before starting the kernel, when no more RomWBW calls are needed.
This works with older RomWBW versions as well, which had HBIOS in nRAM-2 and lower banks were free to use.
Tested with RomWBW 3.2, 3.4, 3.5-dev.101 on Zed Pro.

rc2014: adapt to new RomWBW memory layout

---

Kernel/platform/platform-rpipico/README.md

dc5145b has a comment indicating picotool should be used instead of uf2conv but didn't document how to use picotool. This diff adds the command that worked for me on my rp2350 based board (specifically an adafruit_feather_rp2350).
@veremenko-y: Mentioning you since you're the most likely person to verify I ended up in a reasonable place.
Closes #1123

rpipico: Document picotool usage for filesystem

---

Kernel/platform/platform-coco3/mbr.c

Post- instead of pre- increment populating this table meant HDA1 referred to the 2nd partition, etc.
Brings the logic in coco3-specific td_plt_setup() in line with the usual approach in tinydisk_setup().

coco3: fix populating table of LBAs from CCPT table

---

Kernel/platform/platform-coco3/devtty.c

Note: cursor turned off during clear_lines(), else a spurious cursor remains on tty2.

coco3: initialise both VTs

---

Kernel/platform/platform-coco3/videoll.s

Each interprets twidth as the number of 16-bit words (character, attribute) in a line, where actually it is the number of bytes.
You could see the effect by spawning getty in tty2, setting tty1 to mode 0 (80 column) and issuing a 'clear' command, or by letting it scroll. The operations would touch too much memory and affect tty2.

coco3 video: fix clear_lines, scroll_up, scroll_down

---

Kernel/platform/platform-dragon-mooh/video.s

Optimise TFR usage similar to coco3 patch.
Save 1 byte and 4 cycles computing address within font.
Use the B register within plot_fast to make some savings.  Add 128 to
destination screen address in Y so that subsequent offsest are 8-bit.
Same 128 byte offset in m6847_clear_across, as well as opportunistically
using a post-increment to avoid the need for LEAX 1,X.
Same 128 byte offset in m6847_cursor_on/off.
In m6847_scroll_up/down, use stack ops with U instead of predec/postinc.
Also, fix a possible (maybe not now, but in the future) font corruption;
use LSLB instead of ROLB in fast multiply by 8.

Dragon MOOH video optimisations

---

Kernel/platform/platform-coco3/videoll.s

Any TFR between index registers can be optimised so long as current Z flag is not used (and even then if the destination is U or S).  e.g.
TFR  X,U        ; 2 bytes, 6 cycles
; becomes:
LEAU ,X         ; 2 bytes, 4 cycles
There are also a few places where a pointer is loaded, then replaced with the zero-offset contents pointed to.  6809 indirect addressing can be used here for savings vs extended addressing (the savings go away wrt direct addressing, but I'm pretty sure that's not used here).  e.g.
LDX     _curtty         ; 3 bytes, 6 cycles
LDX     ,X              ; 2 bytes, 5 cycles
; becomes:
LDX     [_curtty]       ; 4 bytes, 10 cycles
RTS can be merged into any PULS right before by adding PC to the registers pulled.
Slight reorder of plot_char to save a branch.
clear_lines does not …

coco3: video optimisations

---

Kernel/platform/platform-coco3/config.h
Kernel/platform/platform-coco3/mbr.c

Needed since 4694e871b.  Not super useful right now though, as raising this number above 6 makes the buffers too large for the current map.  So keeping the default of 4.

coco3: use CONFIG_TD_MAX_PART enumerating CCPT partitions

---

Kernel/cpu-z80u/lowlevel-z80u.S

Delete .export statement in CPU_Z180 part to prevent the following error
with new bintools and compiler.
```
:
Symbol hw_irqvector
While processing: ../../cpu-z80u/lowlevel-z80u.o
exported but undefined
```
Also updates the symbol name in comment.

Delete .export statement in CPU_Z180 part

---

Kernel/platform/platform-trs80/trs80load.s

Fixed 2 bugs in `Kernel/platform/platform-trs80/trs80load.s`:
- Wait state generation not active during kernel loading from floppy;
- One missing byte at the end (255 bytes instead of 256).
Tested with trs80gp and on real hardware Model 4p AZERTY with FreHD.

Fixed 2 bugs in Kernel/platform/platform-trs80/trs80load.s

---

Kernel/platform/platform-dragon-mooh/mem-mooh.s
Kernel/platform/platform-dragon-mooh/tricks.s

Replicating a couple of changes made to the coco3 platform.  MOOH code seems generally tighter though; fewer clear opportunities.

dragon-mooh: minor optimisations

---

Kernel/platform/platform-trs80/trs80.s

It hanged during boot on real hardware (Model 4P with FreHD) because a busy wait loop was missing after the OTIR instruction.
Tested with trs80gp and on real hardware Model 4p with FreHD.

Fixed routine '_hd_xfer_out' in Kernel/platform/platform-trs80/trs80.s:

---

Kernel/platform/platform-coco3/Makefile
Kernel/platform/platform-coco3/coco3.s
Kernel/platform/platform-coco3/devices.c
Kernel/platform/platform-coco3/mbr.c
Kernel/platform/platform-coco3/rules.mk
Kernel/platform/platform-coco3/tricks.s

Couple of build tweaks.
More optimisations, space where it doesn't affect speed.  On top of the 6809 generic ones, visualize6809 even shows a difference...

coco3: optimisations & fixes

---

Kernel/platform/platform-trs80/discard.c

Fixed function `probe_gfx()` in `Kernel/platform/platform-trs80/discard.c`:
- the registers `gfx_x`, `gfx_y` and `gfx_xor` are write-only; we can't get the value back;
- can differentiate between Tandy and Grafyx (original) by trying to write a byte outside the visible range: the Tandy (and the Grafyx clone by IanMav) can do it, but not the original uLabs Grafyx board;
- currently can't differentiate between the Tandy and the Grafyx clone: the Grafyx clone can't XOR the text and the hi-res graphics using the `gfx_xor` register (existing only on the Tandy board).
Tested with trs80gp and on real hardware Model 4p with FreHD and a Grafyx clone from IanMav.

Fixed function 'probe_gfx' in Kernel/platform/platform-trs80/discard.c, not working because of write-only registers.

---

Kernel/platform/platform-trs80/devhd.c

In `if (dev > MAX_HD || parts[dev].g.head == 0 || ... )`: the `dev` variable can't be higher than the maximum subscript of the array `parts[]`. If `dev == MAX_HD` (= 4) then `parts[dev]` is accessed out of bounds (= 0..3).
Changed to `if (dev >= MAX_HD || parts[dev].g.head == 0 || ... )`.
Tested with trs80gp and on real hardware Model 4p with FreHD.

Fixed potential out-of-bounds array access in Kernel/platform/platform-trs80/devhd.c

---

Kernel/platform/platform-trs80/devtty.c

Added AZERTY keyboard support for TRS-80 Model 4/4p in `Kernel/platform/platform-trs80/devtty.c`:
- the AZERTY keyboard layout is enabled by uncommenting the line containing `#define AZERTY`;
- accented and special characters are replaced with other rather important symbols.
Tested with trs80gp and on real hardware Model 4p AZERTY with FreHD.

Added AZERTY keyboard support for TRS-80 Model 4/4p in Kernel/platform/platform-trs80/devtty.c

---

Library/libs/localtim_r.c

The header files time.h and string.h are included twice.

localtim_r: delete duplicate includes

---

Library/libs/crt0_6809_rel.s

Library/libs/crt0_6809_rel.s: fix stashing argv[] as __argv

---

Kernel/platform/platform-rc2014/rc2014.s

The user space was not mapped/unmapped correctly when ch375_rblock() or ch375_wblock() where called.

Fix RC2014 CH375 map/unmap user space
