- Kernel/platform-z80pack/createdrives
- Standalone/ucp.c
This implements a non-interactive mode for UCP, allowing us to use it inside scripts. I've also created a script for z80pack to automatically generate drivea.cpm (boot disk) and drivei.cpm (hard drive with utilities), using UCP this way.
> Noninteractive UCP

- Kernel/filesys.c
- Kernel/start.c
- Kernel/syscall_fs2.c
Some small changes for fs_tab, getdev and newfstab which fix mounting non-root filesystems.
> Filesys fix

- Kernel/platform-msx2/bootrom.s
- Kernel/platform-msx2/crt0.s
- Kernel/platform-msx2/msx2.s
- Kernel/timer.c
Hi Alan,
these are needed for a sd card driver that comes later.
E.-
> more msx2 patches

- Applications/util/Makefile
- Library/Makefile
- Library/libs/Makefile
- Library/tools/fcc.c
Alan
These are some minor improvements to the Makefiles and to fcc. I find them useful.
Will
> Minor improvements to Makefiles etc

- Kernel/Makefile
- Kernel/include/timer.h
- Kernel/inode.c
- Kernel/syscall_fs.c
These were required for me to do a build of the kernel from a clean checkout.
> Fixes to build the kernel

- Kernel/dev/blkdev.c
- Kernel/dev/blkdev.h
- Kernel/dev/devide.c
- Kernel/dev/devide.h
- Kernel/devio.c
- Kernel/include/kernel.h
- Kernel/inode.c
- Kernel/platform-n8vem-mark4/devices.c
- Kernel/platform-p112/devices.c
- Kernel/syscall_fs.c
Here we go again. Now based against alan/master, and tidied up into a series of commits that add the features progressively.
> Cache flush (take 3)

- Kernel/platform-n8vem-mark4/devsdspi.c
based on your socz80 SD driver
> n8vem-mark4: devsdspi - save a byte

- Kernel/platform-p112/devfd.c
- Kernel/platform-p112/devfd2.s
This adds rawflag=1 support to the floppy disk driver on P112. Tried to be conservative with common memory, ended up using only 44 bytes.
> p112: Floppy disk driver (devfd) support for rawflag=1

- Applications/util/prtroot.c
Bug fix: prtroot would write a 0 byte at the end of its output.
The new "-i" flag causes output to go into /etc/mtab instead of to
stdout.
> prtroot: Bug fix, new -i flag to initialise /etc/mtab

- Kernel/dev/devide_discard.c
- Kernel/dev/devsd.c
- Kernel/dev/devsd.h
- Kernel/dev/devsd_discard.c
- Kernel/dev/ds1302.c
- Kernel/dev/ds1302.h
- Kernel/dev/ds1302_discard.c
- Kernel/platform-n8vem-mark4/Makefile
- Kernel/platform-n8vem-mark4/fuzix.lnk
- Kernel/platform-p112/Makefile
- Kernel/platform-p112/fuzix.lnk
Includes required platform changes for n8vem-mark4, p112.
> ds1302, devsd: Split code for the DISCARD segment into separate files.

- Kernel/dev/devsd_discard.c
I believe this will fix one of the bugs that John Coffman reported.
> devsd: Bug fix for SD standard capacity card identification

- Kernel/dev/devsd.c
Fix for the second SD bug John reported.
> devsd: Fix for picky cards

- Applications/util/Makefile
> Update Makefile for factor

- Library/libs/strlen.c
Possibly the world's most boring pull request.
> Correct license on strlen.c

- Kernel/vt.c
this is used by levee,
it works well enough in msx2 to load a 4k file, edit and save.
> vt: return to mode 0 after ESC Y

- Library/include/ctype.h
- Library/libs/Makefile
Library, applications would not build happily without these fixes.
> Library: minor ctype build fixes

- Kernel/dev/devide.c
- Kernel/dev/devide.h
- Kernel/dev/devide_discard.c
- Kernel/platform-p112/devices.c
- Kernel/platform-p112/discard.c
- Kernel/platform-zeta-v2/Makefile
- Kernel/platform-zeta-v2/bootrom.s
- Kernel/platform-zeta-v2/config.h
- Kernel/platform-zeta-v2/devices.c
- Kernel/platform-zeta-v2/discard.c
- Kernel/platform-zeta-v2/fuzix.lnk
- Kernel/platform-zeta-v2/kernel.def
- Kernel/platform-zeta-v2/ppide.c
- Kernel/start.c
A number of changes. Most interesting one is PPIDE support for the Zeta 2 SBC.
> PPIDE for Zeta 2 SBC

- Kernel/dev/devide.c
- Kernel/platform-zeta-v2/ppide.c
> Tiny optimisation for devide_read_data()/devide_write_data()

- Kernel/platform-zeta-v2/Makefile
- Kernel/platform-zeta-v2/README
- Kernel/platform-zeta-v2/diskboot.s
- Kernel/platform-zeta-v2/zeta-v2.s
These changes allow the kernel to be loaded in a broader variety of ways on zeta-v2.
> Make zeta-v2 boot more flexible

- Applications/V7/cmd/sh/main.c
- Applications/V7/cmd/sh/service.c
- Applications/levee/modify.c
- Applications/levee/proto.h
- Applications/util/ssh.c
cc65 makes me sad (but the apps all build now, including sh and levee). Also includes a fix for a mismatched function prototype that was causing gcc to blow up.
> Some more cc65 workarounds

- .travis.yml
- Build/platforms/dragon-nx32.mk
- Build/platforms/msp430fr5969.mk
- Build/rules/targetgcc.rules.mk
- Build/tools/lwtools-ar.sh
- Build/tools/lwtools-ld.sh
Work around some bugs in lwtools' binutils emulation. Also change the Travis setup to use a precompiled version of cc65 (doesn't help build times much, though).
> Some 6809 build system fixes

- Kernel/platform-coco3/coco3.s
- Kernel/platform-coco3/config.h
steps toward swapping on the coco3.
> coco3: implement map_for_swap, swap_map().

- Kernel/platform-coco3/devices.c
- Kernel/platform-coco3/devtty.c
- Kernel/platform-coco3/devtty.h
The start of hi-res graphics for the coco3.
> coco3: add gfx ioctl.

- Kernel/platform-coco3/devtty.c
easy fixes as suggested by Alan.
> coco3: easy fixes

- Kernel/platform-coco3/Makefile
- Kernel/platform-coco3/coco3.s
- Kernel/platform-coco3/devtty.c
- Kernel/platform-coco3/devtty.h
- Kernel/platform-coco3/video.c
- Kernel/platform-coco3/videoll.s
GFXIOC_DRAW is implemented, as stolen from the dragon-nx32 platform :)
> CoCo3: add first of low-level graphics

- Applications/V7/games/arithmetic.c
- Applications/V7/games/backgammon.c
- Applications/V7/games/wump.c
I couldn't make the games run --- mostly failing to flush the buffers before waiting for input. Also, backgammon only shows the game board correctly if it's running on a *teletype*! This corrects these, please a handful of other little oddities.
> Fix the games

- Kernel/platform-coco3/usermem_gime.s
Video-space transfers us uget/uput... make these routine faster.   These routines have already shown a noticeable speed up in disk transfers too.
> coco3: added fast banked/windowing uget / uput xfer routines.

- Build/platforms/msp430fr5969.ld
- Build/platforms/msp430fr5969.ld.h
- Build/rules/targetgcc.rules.mk
- Kernel/lowlevel-msp430x.c
- Kernel/platform-msp430fr5969/config.h
- Kernel/platform-msp430fr5969/msp430fr5969.ld
- Kernel/platform-msp430fr5969/tricks.S
As discussed.
Also rearranges the build system a bit --- there were way to many things to change when changing the size of userspace.
> Enable multiprocess mode for the msp430

- Kernel/platform-dragon-nx32/devtty.c
- Kernel/platform-dragon-nx32/video.s
* Some simple adjustments to video_read's buffer copying
* folded in read and write together routines:  WARNING: self modifying code (merge at your own risk).
> Dragon-nx32: Merge Read/Write, bug fix

- Applications/util/fforth.c
The API's stolen from gforth. It should be possible to write scripts that actually do things now.
> Add support for fetching command line arguments.

- Kernel/platform-coco3/devtty.c
- Kernel/platform-coco3/devtty.h
- Kernel/platform-coco3/video.c
implemented coco3's 16 color text modes.
> CoCo3: color text screens

- Kernel/include/vt.h
- Kernel/platform-coco3/devtty.c
- Kernel/vt.c
Added platform function: vtattr_notify()
> Some more color vt.

- Kernel/bank16k.c
- Kernel/bank16k_low.c
> bank16k's:  pass byte count to swapwrite/read not block count.

- Kernel/platform-coco3/devtty.c
- Kernel/platform-coco3/ttydw.c
A bunch of fixes for bug found.
> Bug fixes for coco3's drivewire tty code

- Kernel/platform-coco3/ttydw.c
* Made port to minor number mapping much more sane.
* fixes "close port bug" and "reopen port bug"
> More fixed for drivewire tty support.

- Kernel/malloc.c
I suspect nobody is using the kernel memory allocator except for me, because it doesn't work --- kmemaddblk() dereferences p without ever assigning to it. I tried to fix it but was unable to understand the code.
This is a complete rewrite using a very slightly tweaked version of the same algorithm. It's been lightly tested, i.e. it doesn't crash when I use it.
(I haven't seen this algorithm before; it's very neat.)
> Rewrite of kernel memory allocator

- Kernel/platform-coco3/coco3.s
> coco3: coco3.s: fix code sections as per Issue: #310.

- Kernel/platform-coco3/devtty.c
Added key repeating.  This hack should work on Dragon too.
> coco3: Add key repeating for keyboard driver

- Applications/util/tar.c
Don't attempt a "Farnsworth Parabox"  situation. It don't work.
> tar.c: don't archive the archive file

- Applications/cave/Makefile.6809
Sorry, some string handling break on gcc6809, so no optimization :( 29k binary
> Adventure: makefile for gcc6809

- Applications/util/kill.c
Is this too much for small boxen?  compiled w/ gcc6809 I get the following bin sizes:
old kill:   2510
new kill: 3149
> kill: more text signals, print list.

- Kernel/tty.c
This is make handling TELNET sessions easier to handle.
> tty.c: add IGNCR. (helps with TCP connections)

- Kernel/platform-coco3/main.c
implement a dummy platform_param() method
> coco3: add dummy platform_param()

- Kernel/platform-coco3/config.h
- Kernel/platform-coco3/drivewire.s
- Kernel/platform-coco3/sdc.s
This makes for much faster exec()'ing.
> coco3: add rawmode=1 support

- Applications/V7/.gitignore
- Applications/games/.gitignore
- Applications/util/.gitignore
- Applications/util/Makefile.6809
- Applications/util/man.1
- Applications/util/man.c
- Applications/util/termcap.c
- Kernel/platform-multicomp09/README
- Standalone/filesystem-src/ucp-extras-script.txt
Replace util/man.c with a different GPL'd version from ELKS, suitably masaged to run under FUZIX. Unlike the old version, this one works without an external nroff (which we didn't have). man.1 as proof
of concept.
ucp-extras-script.txt creates the man/man* directories and inserts man.1
Fixed util/termcap.c so that it compiles on 6809
Added all the new executables created by Tormod's updates to ucp-extras-script.txt
> Apps3 - a working man

- Applications/levee/extern.h
- Library/include/getopt.h
- Library/include/stdio.h
Some simple typos, preventing libc stuff from building
> Fix some typos in libc includes

- Documentation/build-filesystem-ng.md
- Standalone/filesystem-src/build-filesystem-ng
sorry - I thought of this bug earlier but but you merged my last set before I could fix it. Only thing left to do now is dependencies, but I'll leave that for a bit because I need to do some tidy-up work on my port.
> another tweak

- Applications/util/Makefile.6809
- Library/include/stdlib.h
- Library/libs/Makefile.6809
This matches what is being done on the z80 makefiles.
> 6809: compile libs separately

- Applications/MWC/cmd/Makefile.6809
- Applications/V7/cmd/Makefile.6809
- Applications/V7/cmd/sh/Makefile.6809
- Applications/V7/games/Makefile.6809
- Applications/cave/Makefile.6809
- Applications/dw/Makefile.6809
- Applications/games/Makefile.6809
- Applications/levee/Makefile.6809
- Applications/util/Makefile.6809
- Kernel/platform-coco3/.gitignore
- Library/include/6809/stdint.h
- Library/libs/.gitignore
- Library/libs/Makefile.6809
Also add a few build bits to be gitignore'ed.
> 6809 now uses its own stdint.h, not 6502's.

- Kernel/filesys.c
- Kernel/syscall_fs3.c
failure leading into newfile() (parent == NULL), or within newfile()
(and its supporting routines, such as i_open() and ch_link()).
Instead, newfile() uniformly detects and sets errors (or lets errors
from supporting routines propagate upward).  _open() is restructured
to leave udata.u_error as set by newfile(), and thus permit the
actual error code to reach the user.
"touch /x" when you don't have write access to "/" will thus now get
EPERM, not ENFILE.
> Address FIXME of _open(); a catch-all ENFILE was returned for any

- Kernel/lowlevel-6809.s
The simplest 8 bit optimization I could think of.  16 opt may not be worth its additional code size.
!! Added the fix for restoring memory state !! .. I can backout or resubmit a separate PR for discussion if needed.
> 6809: ashrsi3: 8 bit shift optimization

- Kernel/platform-multicomp09/README
- Kernel/platform-multicomp09/devsdc.c
- Kernel/platform-multicomp09/devtty.c
- Kernel/platform-multicomp09/drivewire.s
- Kernel/platform-multicomp09/dwread.s
- Kernel/platform-multicomp09/dwwrite.s
- Kernel/platform-multicomp09/multicomp09.s
- Kernel/platform-multicomp09/platform.def
Add drivewire support to Multicomp. Thanks to Brett for guidance on how to test it.
> Multicomp dw

- Applications/dw/Makefile.6809
- Applications/dw/dwdate.1
- Applications/dw/dwdate.c
- Applications/dw/fuzix-dw.pkg
- Kernel/syscall_proc.c
good for once off'ing during boot from an rc file, or cron'ing.
> dwdate: sets system time from drivewire via userspace

- Applications/build.mk
- Applications/util/Makefile
- Applications/util/Makefile.6809
- Applications/util/fuzix-util.pkg
- Applications/util/uname.c
- Build/platforms/6502test.mk
- Build/platforms/dragon-nx32.mk
- Build/platforms/msp430fr5969.mk
- Build/platforms/trs80.mk
forget about the "Conflicts: Build/platforms/dfboard.mk" in the commit message,
was an artifact from a merge from my dfboard and master branch
> added uname command

- Applications/util/ls.c
sample:
```
66 -rwxr-xr-x   1 root     root        10971 Sep 01 14:32 init
usr:
161 drwxr-xr-x   2 root     root          512 Sep 01 14:32 games
250 drwxr-xr-x   2 root     root          512 Sep 01 14:32 lib
usr/games:
160 -rwxr-xr-x   1 root     root        13718 Sep 01 14:32 backgammon
159 -rwxr-xr-x   1 root     root         8475 Sep 01 14:32 fish
158 -rwxr-xr-x   1 root     root        10084 Sep 01 14:32 wump
usr/lib:
249 -rw-r--r--   1 root     root          997 Sep 01 14:32 liberror.txt
#
```
> refactored ls utility: cleanup, added -R recursive, fixed -r reverse order

- Kernel/Makefile
fix Kernel parallel build
issue #420
> fix Kernel parallel build

- Kernel/dev/net/net_native.c
udata.u_count is mangled by called functions: possibly twice by ringbop(), causing short writes to backing file (when it's full-ish) to fail miserably.
> net_native: udata.u_count is mangled by ringbop()

- Kernel/dev/net/net_native.c
- Kernel/include/kernel.h
- Kernel/include/net_native.h
- Kernel/include/netdev.h
- Kernel/platform-coco3/Makefile
- Kernel/platform-coco3/config.h
- Kernel/platform-coco3/devices.c
- Kernel/platform-coco3/main.c
- Kernel/select.c
- Kernel/syscall_exec16.c
- Kernel/syscall_net.c
- Library/include/sys/socket.h
mostly declaration vs. definition vs. usage fixes
> bring coco3 up to level 2

- Applications/util/cut.c
replace printf() with just a string by a puts()
no need to go on formatting just to print unmodified string
> cut: fix output

- Applications/util/Makefile
- Applications/util/Makefile.6809
- Applications/util/fuzix-util.pkg
- Applications/util/kbdrate.c
- Kernel/vt.c
- Library/include/sys/kd.h
Also fixes vt.c's ioctl: had source and destination flipped.
> simple util to set console key repeat rates

- Applications/util/sync.c
is it possible I haven't built the userspace in 17 days to catch this ?!?!
> sync: gcc complains about sync being void

- Kernel/platform-multicomp09/multicomp09.s
yr fix was not quite complete.
> make multicomp09 compile again

- Applications/util/Makefile
- Applications/util/termcap.c
- Kernel/tools/binman.c
Alan -- some minor fixes enclosed.
> Minor build fixes

- Kernel/platform-zeta-v2/Makefile
- Kernel/platform-zeta-v2/zeta-v2.s
Alan -- one fix for Zeta-v2 (would not boot), and a couple of minor improvements.
> Fixes for zeta-v2 platform

- Kernel/platform-coco3/ttydw.c
From Michael Furman: improves interactivity on clients, but probably makes servers slower.
> coco3: drivewire: maintain faster polling for short while after a putc.

- Applications/netd/dig.c
Make dig use /etc/resolv.conf and/or "@" prefix to set DNS server.  Sure beats my hard-coded local dns server :)
> Dig: beef it up.

- Kernel/include/kernel.h
- Kernel/platform-n8vem-mark4/discard.c
- Kernel/platform-n8vem-mark4/main.c
- Kernel/platform-p112/discard.c
- Kernel/platform-p112/main.c
- Kernel/platform-zeta-v2/discard.c
- Kernel/platform-zeta-v2/main.c
- Kernel/platform-zeta-v2/zeta-v2.s
> Optimisations

- Applications/netd/netd.c
This allows the uip engine to route locally destined eth frames back to ourselves by short circuiting the frames just before they get sent on network.
> netd: route locally destined eth frames back to ourselfs.

- Kernel/platform-trs80/trs80load.s
In order to run Fuzix on a real TRS-80 Model 4 some corrections have to be made to the bootloader:
- The correct mode was not selected, Video Page #1 needs to be selected. The emulator SDLTRS does not behave correctly; on a real Model 4 Video Page #0 starts on FC00 with a distorted screen as result. So: OUT (0x84),#0x86 is working correctly.
- Stackpointer out of the way on 0xEE00, doesn't overwrite code.
- The ctc6845 registers are not loaded correctly, they must be read in reverse order. So INC HL must be DEC HL and the label must be put at the end of the table.
- The Clear Screen routine was not implemented correctly.
- On a real Model 4 a formatted floppy must be used to boot. This will be a SDDD disk, 40 tracks, formatted for TRS-DOS 6 or LS-DOS 6. These formatted disks have 18 …
> Update trsload80.s to work on real hardware

- Applications/netd/Makefile.6809
- Applications/netd/ntpdate.c
No, not full-blown ntp (or sntp even), but good enough for set the system clock from ntp.
> netd: proggie to set system time from ntp server

- Kernel/platform-coco3/dwread.s
This adds a proper timeout to emulators and fpga projects using the "becker" port for drivewire.
> Add a timeout to dw-over-becker, simplify.

- Applications/netd/coconic.c
make coconic faster, and move i/o base to an multi-pak friendly address.
> coconic: change to static address on init, enable 16 bit xfers

- Library/include/sys/netdev.h
> libs: missed a header.

- Kernel/platform-msx2/config.h
- Kernel/platform-msx2/devmegasd.c
- Kernel/platform-msx2/discard.c
- Kernel/platform-msx2/msx2.s
With this the msx2 kernel is able to boot rootfs-z80-32 from fuzix.org, 
some random hangs are also gone.
> fix msx2 port

- Applications/util/tar.c
fixing bugs found while writing a cassette tape driver.
> simple fixes for 'tar'

- Kernel/platform-msx2/config.h
- Kernel/platform-msx2/crt0.s
- Kernel/platform-msx2/devmegasd.c
- Kernel/platform-msx2/fuzix.lnk
- Kernel/platform-msx2/kernel.def
- Kernel/platform-msx2/main.c
- Kernel/platform-msx2/msx2.s
slowly catching up with all the available features
> msx2: use dynamic buffers

- Applications/fview/fview.c
amazing this never reared it's head before now....
> fview: bug fix endian checker

- Kernel/platform-coco3/Makefile
- Kernel/platform-coco3/build
More clean up of platform's makefile, simplified build script
> coco3: clean up make / build script

- Kernel/filesys.c
> fs: oops... reserve debugging in fs :)

- Applications/MWC/cmd/fuzix-cmd.pkg
- Applications/MWC/cmd/make.h
fix a prototype, and add make to filesystem.
> Tidy 'make'

- Applications/util/fsck.c
- Standalone/fsck.c
parallel fixes to fsck and standalone fsck:
1. still trying to pass 32 bits to swizzle16
2. always returns with error upon "continuing"
> fsck: fix some more bugs

- Applications/netd/Makefile.6809
- Applications/netd/fuzix-netd.pkg
- Applications/netd/htget.c
un-decapitate content, add to 6809 + fs build script.
> htget: quick fixes

- Applications/netd/Makefile.6809
- Applications/netd/fuzix-netd.pkg
> irc: 6809 compile, add to fs

- Applications/util/remount.c
- Kernel/platform-coco3/devtty.c
> Easy fixes

- Library/libs/putpwent.c
this was leaving /etc/passwd all funny.
> pwd: putpwent: wrong order of fields.

- Standalone/filesystem-src/build-filesystem-ng
Allows one to use Neal's filesystem builder non-interactively.
> build: add fsck -y passing to buildscript

- Applications/util/tar.c
addresses:
https://github.com/EtchedPixels/FUZIX/issues/601
https://github.com/EtchedPixels/FUZIX/issues/602
Non-existent directories are made with ownership as per gnu tar: the UID/GID of tar process.
> tar: issue fixes

- Library/Makefile
- Library/libs/Makefile.z80
> Makefile: z80: fix the 'clean' target and make it work again

- Kernel/platform-rc2014/Makefile
> rc2014: dont fail to build if ../rc2014_root_fs doesnt exist

- Applications/games/hamurabi.c
> games: fix hamurabi build by expliciting void types

- README.md
Add build status indicator and link to the build results
> README: show build status and link to build results

- .travis.yml
> travis: add 65xx build deps to let the build start

- Kernel/Makefile
- Kernel/cpu-z80/image.mk
> tools: build trslabel

- Kernel/platform-coco2cart/bootstrap.s
- Kernel/platform-coco2cart/bootstrap_sdc.s
- Kernel/platform-coco2cart/devsdc.c
A few things I've noticed trying to get fuzix booting.
> some fixes for coco2cart SDC support

- Applications/cave/fuzix-cave.pkg
location changed here:
https://github.com/EtchedPixels/FUZIX/commit/51878ccaaf9cc69da8a8ed4d354e5eedf7625d78
> cave: install database to where advent expects it

- Kernel/platform-coco3/config.h
- Kernel/platform-coco3/devtty.c
- Kernel/platform-coco3/main.c
-or- "Keeping up with the Jones'"
> coco3: tty_setup, and dummy copyright

- Applications/games/fweep.c
... https://github.com/EtchedPixels/sdcc compiles without errors ...
> fweep: fix build with sdcc 3.7.1 for Travis

- Applications/util/tar.c
Implements blocking factor and fixes a few stat.mode problems.
> Tar take 2

- Applications/cursesgames/invaders.c
> games: invaders: fail if TERM not set

- Applications/games/Makefile.6809
fixes compile, but yields some gobbly-gook at screen when playing.
> games: 6809: link to termcap for CUSS

- README.md
Fix the processor name at MD file.
> Fix 8085 processor name.

- Kernel/syscall_exec16.c
- Library/libs/crt0_6809.s
- Library/libs/crt0nostdio_6809.s
some easy fixes for the new bin header changes.  I get to init now, but now my sh is complaining of "membad", or just crashing.
> Header fix

- Library/libs/atoi.c
- Library/libs/atol.c
> fix atoi/atol

- Kernel/platform-esp8266/Makefile
- Standalone/Makefile
- Standalone/mkftl.1
- Standalone/mkftl.c
As it's going to be used by the Raspberry Pi Pico port too, I've moved it to Standalone, polished it up so that the parameters can be set on the command line, and added a man page.
> Move mkftl into Standalone

- Kernel/platform-coco3/config.h
- Kernel/platform-coco3/devices.c
- Kernel/platform-coco3/fuzix.link
networking off until further net dev.  this agets coco3 building again
> coco3: get it building again

- .github/workflows/c-cpp.yml
This makes the esp8266 build go green. Still no idea about the sbcv2, though.
> One last piece of CI tidying

- Applications/netd/netd.c
- Kernel/dev/net/net_native.c
This solves a huge problem with userspace network related programs
that could be started only once, as any subsequent run was not
possible due to the lack of free sockets.
> syscall_net: release closed socket to avoid running out of free sockets

- .github/workflows/continuous-integration.yml
- Kernel/platform-appleiie/Makefile
- Kernel/platform-appleiie/appleii.s
- Kernel/platform-appleiie/tricks.s
BTW, i'm using vi and i noticed a lot of spacing issues, shall we enforce some spacing/style?
> appleiie: fix build

- Standalone/filesystem-src/build-filesystem
- Standalone/filesystem-src/build-mini-filesystem
- Standalone/filesystem-src/build-tm4c129x-filesystem
I've found it annoying that the issue is either not created or has no version in it.
> versioning: make sure VERSION is always in use

- Kernel/platform-rc2014/crt0.s
- Kernel/platform-rcbus-z180/crt0.s
- Kernel/platform-zx+3/devtty.c
- Kernel/tools/modlib-z80.c
Nothing impressive really, just things I've bumped into.
> NFC: various cleanups

- Kernel/cpu-riscv32/types.h
Just random nit I've bumped on while looking at the most recent additions to FUZIX.
> NFC: these are not ARM's types

- Applications/MWC/cmd/asz80/Makefile.8080
- Applications/MWC/cmd/asz80/Makefile.common
- Applications/MWC/cmd/asz80/Makefile.z80
- Applications/SmallC/Makefile
- Applications/SmallC/Makefile.8080
- Applications/SmallC/Makefile.armm0
- Applications/SmallC/Makefile.armm4
- Applications/SmallC/Makefile.common
- Applications/SmallC/Makefile.linux
- Applications/SmallC/Makefile.z80
- Applications/games/Makefile.armm0
- Applications/games/Makefile.armm4
- Applications/games/Makefile.common
- Applications/games/Makefile.z80
- Applications/ld09/Makefile.8080
- Applications/ld09/Makefile.armm0
- Applications/ld09/Makefile.armm4
- Applications/ld09/Makefile.common
- Applications/ld09/Makefile.z80
- Applications/netd/Makefile.z80
- Applications/ue/Makefile.z80
- Kernel/Makefile
- Library/Makefile
A lot of executables was left behind when doing `make clean`.
> Makefiles: help cleaning after itself

- Applications/MWC/cmd/Makefile.armm0
- Applications/V7/cmd/Makefile.armm0
- Applications/V7/cmd/sh/Makefile.armm0
- Applications/V7/games/Makefile.armm0
- Applications/as09/Makefile.armm0
- Applications/cave/Makefile.armm0
- Applications/cursesgames/Makefile.armm0
- Applications/flashrom/Makefile.armm0
- Applications/games/Makefile.armm0
- Applications/ld09/Makefile.armm0
- Applications/levee/Makefile.armm0
- Applications/ue/Makefile.armm0
- Applications/util/Makefile.armm0
commit 2b67da35f3d38053686b4a40891df16fa3ba240f
Author: Alan Cox <etchedpixels@gmail.com>
Date:   Sat Sep 9 10:26:17 2023 +0100
Applications: move rule files and tidy up a bit
missed to convert these Makefile.armm0, fix it.
> Applications: fix rpipico CI build

- .github/workflows/continuous-integration.yml
- Applications/assembler/Makefile.6303
- Applications/assembler/Makefile.6502
- Applications/assembler/Makefile.65c816
- Applications/assembler/Makefile.6800
- Applications/assembler/Makefile.6803
- Applications/assembler/Makefile.68hc11
- Applications/assembler/Makefile.8080
- Applications/assembler/Makefile.8085
- Applications/assembler/Makefile.common
- Applications/assembler/Makefile.wrx6
- Applications/assembler/Makefile.z80
- Kernel/platform/platform-dragon-mooh/fuzix-platform-dragon-mooh.pkg
- Kernel/platform/platform-dragon-mooh/rules.mk
- Kernel/platform/platform-dragon-mooh/userspace
- Makefile
This makes the CI go green again.
And dragon-mooh build again (but not running since the post-v0.4 turmoil).
> Build and CI fixes

- .github/workflows/continuous-integration.yml
- Applications/assembler/Makefile.6303
- Applications/assembler/Makefile.6502
- Applications/assembler/Makefile.65c816
- Applications/assembler/Makefile.6800
- Applications/assembler/Makefile.6803
- Applications/assembler/Makefile.68hc11
- Applications/assembler/Makefile.8080
- Applications/assembler/Makefile.8085
- Applications/assembler/Makefile.common
- Applications/assembler/Makefile.wrx6
- Applications/assembler/Makefile.z80
- Applications/util/Makefile.common
- Applications/util/init.c
- Build/tests/test-dragon-mooh
- Build/tests/test-dragon-mooh-prepare
- Kernel/platform/platform-dragon-mooh/config.h
- Kernel/platform/platform-dragon-mooh/fuzix-platform-dragon-mooh.pkg
- Kernel/platform/platform-dragon-mooh/rules.mk
- Kernel/platform/platform-dragon-mooh/userspace
- Kernel/platform/platform-dragon-nx32/devtty.c
- Kernel/platform/platform-dragon-nx32/userspace/rc.ci_testing
- Makefile
<s>This needs a few improvements still, in order to not affect the normal builds.</s>
EDIT: Should be fine with normal builds now.
> CI: Add dragon-mooh with test-run in XRoar

- Tools/build-6303
- Tools/build-6502
- Tools/build-65c816
- Tools/build-6800
- Tools/build-6803
- Tools/build-6809
- Tools/build-68hc11
- Tools/build-armm0
- Tools/build-armm4
- Tools/build-esp32
- Tools/build-esp8266
- Tools/build-ns32k
- Tools/build-riscv32
And add tool checking file for esp32, fix the one for esp8266.
> Return error if tool check fails

- Kernel/platform/platform-rpipico/Makefile
- Kernel/platform/platform-rpipico/config.h
- Kernel/platform/platform-rpipico/misc.c
- Kernel/platform/platform-rpipico/pico_ioctl.h
- Kernel/platform/platform-rpipico/update-flash.sh
- Kernel/platform/platform-rpipico/utils/Makefile
- Kernel/platform/platform-rpipico/utils/pico
- Kernel/platform/platform-rpipico/utils/picoioctl.c
Base on the feedback from #1050
> Pi Pico IOCTL device

- Applications/CC/Makefile.armm0
- Applications/V7/cmd/Makefile.armm0
- Applications/ar/Makefile.armm0
- Applications/assembler/Makefile.armm0
- Applications/cpp/Makefile.armm0
- Applications/games/Makefile.armm0
- Applications/util/fuzix-util.pkg
- Kernel/platform/platform-rpipico/Makefile
- Kernel/platform/platform-rpipico/devtty.c
- Kernel/platform/platform-rpipico/fuzix-platform-rpipico.pkg
- Kernel/platform/platform-rpipico/utils/Makefile
- Library/Makefile
- Library/libs/Makefile.armm0
32MB image now can be used on SD card
> rpipico: Added support for build-filesystem-ng

- Applications/util/man.1
- Applications/util/man.c
For testing manpages in fuzix format
> man: Added local search mode

- Applications/netd/dig.c
- Applications/netd/echoping.c
- Kernel/dev/net/net_w5x00.c
- Kernel/syscall_net.c
I'm on a quest to get dig (and UDP generally) working on Z180/Wiznet. As reported in #1093 it is not working.
This half solves it - UDP datagrams are now sent correctly. Fixed up dig and echoping a bit in the process of trying to diagnose what was wrong.
Continuing to work on figuring out why UDP responses to us aren't read correctly.
> Some UDP fixes

- Kernel/platform/platform-rpipico/Makefile
- Kernel/platform/platform-rpipico/README.md
Fixed the mess I did in the `Makefile`. Tested on both pico and pico2 boards.
Should finally fix #1123 properly.
> pico: Proper fix for pico and pico2 uf2 images build

- Kernel/platform/platform-rosco-r2/Makefile
- Kernel/platform/platform-rosco-r2/README.md
- Kernel/platform/platform-rosco-r2/config.h
- Kernel/platform/platform-rosco-r2/crt0.S
- Kernel/platform/platform-rosco-r2/devch375.c
- Kernel/platform/platform-rosco-r2/devch375.h
- Kernel/platform/platform-rosco-r2/devch375_discard.c
- Kernel/platform/platform-rosco-r2/devices.c
- Kernel/platform/platform-rosco-r2/devtty.c
- Kernel/platform/platform-rosco-r2/devtty.h
- Kernel/platform/platform-rosco-r2/fuzix.ld
- Kernel/platform/platform-rosco-r2/kernel.def
- Kernel/platform/platform-rosco-r2/libc.c
- Kernel/platform/platform-rosco-r2/main.c
- Kernel/platform/platform-rosco-r2/mk_fs_img
- Kernel/platform/platform-rosco-r2/p68000.S
- Kernel/platform/platform-rosco-r2/target.mk
- Kernel/platform/platform-rosco-r2/tricks.S
I think this is ready for inclusion, but let me know if things need fixing. Thanks!
> Kernel/platform/platform-rosco-r2: A port of FUZIX to the Rosco r2 m68k SBC.

- Kernel/mm/bank16k.c
Otherwise it loses pages.
Only really visible if you start playing with chmem.
> Kernel/mm/bank16k.c: add new pages below existing common
